-- 20261008032829_init (generated by lidza gen from schema.lidza)
DROP TABLE auth_member;
DROP TABLE auth_connection;
DROP TABLE auth_identity;
DROP TABLE auth_user;
DROP TABLE auth_account;
DROP TABLE auth_token;
DROP TABLE auth_session;
