-- 20261008050715_create_calendar_reply_grant_create_calendar_dispatch_create_ (generated by lidza gen from schema.lidza)
DROP TABLE reminder_notice;
DROP TABLE calendar_reminder;
DROP TABLE calendar_dispatch;
DROP TABLE calendar_reply_grant;
