-- 20261009031943_alter_setup_probe (generated by lidza gen from schema.lidza)
CREATE INDEX setup_probe_created_at_idx ON setup_probe (created_at);
CREATE INDEX setup_probe_kind_fingerprint_state_created_at_idx ON setup_probe (kind, fingerprint, state, created_at);
