-- 20261008215111_alter_smip_inbox (generated by lidza gen from schema.lidza)
ALTER TABLE smip_inbox DROP COLUMN name;
ALTER TABLE smip_inbox DROP COLUMN body;
ALTER TABLE smip_inbox DROP COLUMN stream;
ALTER TABLE smip_inbox DROP COLUMN recipient;
ALTER TABLE smip_inbox DROP COLUMN sender;
