-- 20261008195449_create_audit_event (generated by lidza gen from schema.lidza)
CREATE TABLE audit_event (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  at timestamptz NOT NULL DEFAULT now(),
  actor text NOT NULL,
  action text NOT NULL,
  resource text NOT NULL DEFAULT '',
  scope text NOT NULL DEFAULT '',
  outcome text NOT NULL,
  request_id text NOT NULL DEFAULT '',
  meta jsonb NOT NULL
);
CREATE INDEX audit_event_at_id_idx ON audit_event (at, id);
CREATE INDEX audit_event_actor_at_idx ON audit_event (actor, at);
CREATE INDEX audit_event_scope_at_idx ON audit_event (scope, at);
