-- 20261009030949_create_setup_probe (generated by lidza gen from schema.lidza)
CREATE TABLE setup_probe (
  id uuid PRIMARY KEY,
  kind text NOT NULL,
  subject text NOT NULL,
  revision integer NOT NULL,
  fingerprint text NOT NULL,
  state text NOT NULL DEFAULT 'started',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX setup_probe_subject_kind_created_at_idx ON setup_probe (subject, kind, created_at);
