-- 20261008053602_create_meeting_create_meeting_participant_create_meeting_web (generated by lidza gen from schema.lidza)
CREATE TABLE meeting (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  request_id uuid NOT NULL,
  name varchar(200) NOT NULL,
  created_by text NOT NULL,
  ended_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX meeting_workspace_id_idx ON meeting (workspace_id);
CREATE UNIQUE INDEX meeting_workspace_id_request_id_key ON meeting (workspace_id, request_id);
CREATE TABLE meeting_participant (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL REFERENCES meeting(id),
  subject text NOT NULL,
  token_expires_at timestamptz NOT NULL,
  joined boolean NOT NULL DEFAULT false,
  session_id text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX meeting_participant_meeting_id_idx ON meeting_participant (meeting_id);
CREATE UNIQUE INDEX meeting_participant_meeting_id_subject_key ON meeting_participant (meeting_id, subject);
CREATE TABLE meeting_webhook (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id text NOT NULL UNIQUE,
  checksum text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
