-- 20261008034629_create_workspace_role_create_invitation (generated by lidza gen from schema.lidza)
CREATE TYPE workspace_role AS ENUM ('owner', 'admin', 'member');
CREATE TABLE invitation (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  email varchar(254) NOT NULL,
  role workspace_role NOT NULL,
  token_hash text NOT NULL UNIQUE,
  invited_by text NOT NULL,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX invitation_workspace_id_idx ON invitation (workspace_id);
