-- 20261009023533_create_auth_owner_claim (generated by lidza gen from schema.lidza)
CREATE TABLE auth_owner_claim (
  id text PRIMARY KEY,
  token_hash text NOT NULL,
  subject text,
  claimed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
