-- 20261008032829_init (generated by lidza gen from schema.lidza)
CREATE TABLE auth_session (
  id text PRIMARY KEY,
  subject text NOT NULL,
  refresh_hash text NOT NULL UNIQUE,
  prev_refresh_hash text,
  rotated_at timestamptz,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  remember boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_session_subject_idx ON auth_session (subject);
CREATE TABLE auth_token (
  id text PRIMARY KEY,
  purpose text NOT NULL,
  subject text NOT NULL,
  hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_token_purpose_idx ON auth_token (purpose);
CREATE INDEX auth_token_subject_idx ON auth_token (subject);
CREATE TABLE auth_account (
  subject text PRIMARY KEY,
  label text,
  disabled_at timestamptz,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE auth_user (
  subject text PRIMARY KEY,
  email text UNIQUE,
  name text,
  password_hash text,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE auth_identity (
  id text PRIMARY KEY,
  provider text NOT NULL,
  provider_subject text NOT NULL,
  subject text NOT NULL,
  email text,
  name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_identity_provider_idx ON auth_identity (provider);
CREATE INDEX auth_identity_subject_idx ON auth_identity (subject);
CREATE TABLE auth_connection (
  id text PRIMARY KEY,
  owner text NOT NULL,
  provider text NOT NULL,
  subject text NOT NULL,
  login text NOT NULL DEFAULT '',
  scopes text NOT NULL DEFAULT '',
  token_type text NOT NULL DEFAULT '',
  access_sealed text NOT NULL,
  refresh_sealed text NOT NULL DEFAULT '',
  expires_at timestamptz,
  reconnect boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX auth_connection_owner_provider_key ON auth_connection (owner, provider);
CREATE TABLE auth_member (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject text NOT NULL,
  scope text NOT NULL DEFAULT '',
  role text NOT NULL,
  granted_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX auth_member_subject_scope_role_key ON auth_member (subject, scope, role);
CREATE INDEX auth_member_scope_role_idx ON auth_member (scope, role);
