-- 20261008041407_create_drive_folder_create_drive_file_create_file_version_cr (generated by lidza gen from schema.lidza)
DROP TABLE share_grant;
DROP TABLE upload_chunk;
DROP TABLE upload_session;
DROP TABLE file_version;
DROP TABLE drive_file;
DROP TABLE drive_folder;
