-- 20261008044005_create_attendance_create_calendar_create_calendar_event_crea (generated by lidza gen from schema.lidza)
DROP TABLE event_attendee;
DROP TABLE event_exception;
DROP TABLE calendar_event;
DROP TABLE calendar;
DROP TYPE attendance;
