-- 20261008231529_create_server_setup (generated by lidza gen from schema.lidza)
CREATE TABLE server_setup (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject text NOT NULL DEFAULT '',
  workspace_id uuid,
  revision integer NOT NULL DEFAULT 0,
  published_revision integer NOT NULL DEFAULT 0,
  draft text NOT NULL DEFAULT '',
  published text NOT NULL DEFAULT '',
  step text NOT NULL DEFAULT 'server',
  published_at timestamptz
);
