-- 20261008181017_alter_mailbox_alter_mail_item_create_mail_label_create_mail_ (generated by lidza gen from schema.lidza)
ALTER TABLE mailbox ADD COLUMN signature text NOT NULL DEFAULT '';
ALTER TABLE mail_item ADD COLUMN message_id text NOT NULL DEFAULT '';
ALTER TABLE mail_item ADD COLUMN in_reply_to text NOT NULL DEFAULT '';
ALTER TABLE mail_item ADD COLUMN references_header text NOT NULL DEFAULT '';
CREATE TABLE mail_label (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  mailbox_id uuid NOT NULL REFERENCES mailbox(id),
  name varchar(40) NOT NULL
);
CREATE INDEX mail_label_mailbox_id_idx ON mail_label (mailbox_id);
CREATE UNIQUE INDEX mail_label_mailbox_id_name_key ON mail_label (mailbox_id, name);
CREATE TABLE mail_tag (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL REFERENCES mail_item(id),
  label_id uuid NOT NULL REFERENCES mail_label(id)
);
CREATE INDEX mail_tag_item_id_idx ON mail_tag (item_id);
CREATE INDEX mail_tag_label_id_idx ON mail_tag (label_id);
CREATE UNIQUE INDEX mail_tag_item_id_label_id_key ON mail_tag (item_id, label_id);
