-- 20261008035648_create_mail_folder_create_mailbox_create_mail_item_create_ma (generated by lidza gen from schema.lidza)
DROP TABLE mail_attachment;
DROP TABLE mail_item;
DROP TABLE mailbox;
DROP TYPE mail_folder;
