-- 20261008033100_create_workspace_create_contact (generated by lidza gen from schema.lidza)
CREATE TABLE workspace (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(120) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE contact (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  name varchar(200) NOT NULL,
  email varchar(254) NOT NULL,
  company varchar(200) NOT NULL DEFAULT '',
  phone varchar(80) NOT NULL DEFAULT '',
  favorite boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX contact_workspace_id_idx ON contact (workspace_id);
