-- 20261008061209_alter_file_version_alter_upload_chunk (generated by lidza gen from schema.lidza)
CREATE INDEX file_version_object_key_idx ON file_version (object_key);
CREATE INDEX upload_chunk_object_key_idx ON upload_chunk (object_key);
