-- 20261008181017_alter_mailbox_alter_mail_item_create_mail_label_create_mail_ (generated by lidza gen from schema.lidza)
DROP TABLE mail_tag;
DROP TABLE mail_label;
ALTER TABLE mail_item DROP COLUMN references_header;
ALTER TABLE mail_item DROP COLUMN in_reply_to;
ALTER TABLE mail_item DROP COLUMN message_id;
ALTER TABLE mailbox DROP COLUMN signature;
