-- 20261008041407_create_drive_folder_create_drive_file_create_file_version_cr (generated by lidza gen from schema.lidza)
CREATE TABLE drive_folder (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  parent_id uuid,
  name varchar(200) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX drive_folder_workspace_id_idx ON drive_folder (workspace_id);
CREATE TABLE drive_file (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  folder_id uuid,
  name varchar(200) NOT NULL,
  content_type text NOT NULL,
  size integer NOT NULL,
  current_version integer NOT NULL DEFAULT 1,
  trashed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX drive_file_workspace_id_idx ON drive_file (workspace_id);
CREATE TABLE file_version (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  file_id uuid NOT NULL REFERENCES drive_file(id),
  number integer NOT NULL,
  object_key text NOT NULL,
  checksum text NOT NULL,
  size integer NOT NULL,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX file_version_file_id_idx ON file_version (file_id);
CREATE UNIQUE INDEX file_version_file_id_number_key ON file_version (file_id, number);
CREATE TABLE upload_session (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  subject text NOT NULL,
  file_id uuid,
  folder_id uuid,
  name text NOT NULL,
  content_type text NOT NULL,
  expected_size integer NOT NULL,
  base_version integer NOT NULL,
  expires_at timestamptz NOT NULL,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX upload_session_workspace_id_idx ON upload_session (workspace_id);
CREATE TABLE upload_chunk (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES upload_session(id),
  number integer NOT NULL,
  size integer NOT NULL,
  checksum text NOT NULL,
  object_key text NOT NULL
);
CREATE INDEX upload_chunk_session_id_idx ON upload_chunk (session_id);
CREATE UNIQUE INDEX upload_chunk_session_id_number_key ON upload_chunk (session_id, number);
CREATE TABLE share_grant (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  file_id uuid NOT NULL REFERENCES drive_file(id),
  token_hash text NOT NULL UNIQUE,
  target_email text NOT NULL DEFAULT '',
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX share_grant_file_id_idx ON share_grant (file_id);
