-- 20261008200508_create_drive_preview (generated by lidza gen from schema.lidza)
CREATE TABLE drive_preview (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  file_id uuid NOT NULL UNIQUE REFERENCES drive_file(id),
  version integer NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  object_key text NOT NULL DEFAULT '',
  checksum text NOT NULL DEFAULT '',
  content_type text NOT NULL DEFAULT '',
  width integer NOT NULL DEFAULT 0,
  height integer NOT NULL DEFAULT 0,
  truncated boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);
