-- 20261008034606_create_job_create_job_schedule (generated by lidza gen from schema.lidza)
CREATE TABLE job (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind text NOT NULL,
  payload jsonb NOT NULL,
  state text NOT NULL DEFAULT 'pending',
  run_at timestamptz NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 5,
  locked_at timestamptz,
  finished_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  unique_key text
);
CREATE INDEX job_state_run_at_idx ON job (state, run_at);
CREATE UNIQUE INDEX job_kind_unique_key_key ON job (kind, unique_key);
CREATE TABLE job_schedule (
  kind text PRIMARY KEY,
  spec text NOT NULL,
  next_run_at timestamptz NOT NULL,
  last_run_at timestamptz,
  last_job_id uuid,
  updated_at timestamptz NOT NULL DEFAULT now()
);
