-- 20261008215111_alter_smip_inbox (generated by lidza gen from schema.lidza)
ALTER TABLE smip_inbox ADD COLUMN sender text NOT NULL DEFAULT '';
ALTER TABLE smip_inbox ADD COLUMN recipient text NOT NULL DEFAULT '';
ALTER TABLE smip_inbox ADD COLUMN stream text NOT NULL DEFAULT '';
ALTER TABLE smip_inbox ADD COLUMN body text NOT NULL DEFAULT '';
ALTER TABLE smip_inbox ADD COLUMN name text NOT NULL DEFAULT '';
