-- 20261008053602_create_meeting_create_meeting_participant_create_meeting_web (generated by lidza gen from schema.lidza)
DROP TABLE meeting_webhook;
DROP TABLE meeting_participant;
DROP TABLE meeting;
