// Code generated by lidza gen from lidza.json. DO NOT EDIT.

package main

import "github.com/agim/lidza"

// packs lists the packs lidza.json enables; none yet. `lidza pack scaffold <name>` adds one.
func packs() []lidza.Pack { return nil }
