import React from "react";
import {
  Archive,
  ArrowUpRight,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  ContactRound,
  Delete,
  File,
  FileArchive,
  FilePenLine,
  FileText,
  Files,
  Folder,
  FolderPlus,
  Folders,
  Form,
  Forward,
  Group,
  HardDrive,
  Hash,
  Image,
  Inbox,
  LayoutGrid,
  List,
  Mail,
  Maximize2,
  MessageCircle,
  MessagesSquare,
  Mic,
  MicOff,
  Monitor,
  Moon,
  Option,
  Orbit,
  PanelLeftOpen,
  Paperclip,
  Phone,
  PhoneOff,
  Plus,
  Reply,
  ReplyAll,
  Search,
  Section,
  Send,
  Share,
  Share2,
  Sheet,
  ShieldAlert,
  Split,
  SquarePen,
  Star,
  Sun,
  Table,
  Tag,
  Text,
  ThumbsUp,
  Trash2,
  Undo2,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  VideoOff,
  X,
} from "lucide-react";
const iconMap = {
  forward: Forward,
  inbox: Inbox,
  star: Star,
  clock: Clock,
  send: Send,
  "file-pen-line": FilePenLine,
  archive: Archive,
  "shield-alert": ShieldAlert,
  "trash-2": Trash2,
  text: Text,
  section: Section,
  x: X,
  file: File,
  paperclip: Paperclip,
  orbit: Orbit,
  folders: Folders,
  "square-pen": SquarePen,
  list: List,
  search: Search,
  option: Option,
  mail: Mail,
  delete: Delete,
  tag: Tag,
  "panel-left-open": PanelLeftOpen,
  "maximize-2": Maximize2,
  "file-text": FileText,
  "calendar-days": CalendarDays,
  "arrow-up-right": ArrowUpRight,
  reply: Reply,
  "reply-all": ReplyAll,
  "undo-2": Undo2,
  group: Group,
  split: Split,
  plus: Plus,
  hash: Hash,
  user: User,
  users: Users,
  "thumbs-up": ThumbsUp,
  form: Form,
  check: Check,
  video: Video,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  sheet: Sheet,
  image: Image,
  "file-archive": FileArchive,
  folder: Folder,
  "folder-plus": FolderPlus,
  upload: Upload,
  "hard-drive": HardDrive,
  "layout-grid": LayoutGrid,
  share: Share,
  "share-2": Share2,
  "user-plus": UserPlus,
  table: Table,
  files: Files,
  phone: Phone,
  "message-circle": MessageCircle,
  mic: Mic,
  "mic-off": MicOff,
  "video-off": VideoOff,
  "phone-off": PhoneOff,
  "messages-square": MessagesSquare,
  "contact-round": ContactRound,
  moon: Moon,
  sun: Sun,
  monitor: Monitor,
};
export function h(type, props, ...children) {
  if (type === "i" && props?.["data-lucide"]) {
    const Component = iconMap[props["data-lucide"]];
    if (!Component) throw new Error("Unknown icon: " + props["data-lucide"]);
    return React.createElement(Component, { size: 16, "aria-hidden": true });
  }
  if (props?.["data-tooltip"])
    props = { ...props, title: props["data-tooltip"] };
  return React.createElement(type, props, ...children);
}
export const icon = (n) => h("i", { "data-lucide": n, "aria-hidden": true });
export const btn = (text, action, i, cls = "", props = {}) =>
  h(
    "button",
    {
      type: "button",
      onClick: action,
      className: "cursor-interaction " + cls,
      ...props,
    },
    i ? icon(i) : null,
    text,
  );
export const avatar = (name, cls = "") =>
  h(
    "span",
    { className: "av " + cls },
    name
      .split(" ")
      .map((n) => n[0])
      .slice(0, 2)
      .join(""),
  );
export const search = (value, set, placeholder) =>
  h(
    "label",
    { className: "searchbox" },
    icon("search"),
    h("input", {
      value,
      onChange: (e) => set(e.target.value),
      placeholder,
      "aria-label": placeholder,
    }),
  );
