// Code generated by lidza gen from lidza.json. DO NOT EDIT.

package app

import (
	"github.com/agim/lidza"

	auth "github.com/agim/lidza/packs/auth"
	db "github.com/agim/lidza/packs/db"
	jobs "github.com/agim/lidza/packs/jobs"
	mail "github.com/agim/lidza/packs/mail"
	storage "github.com/agim/lidza/packs/storage"
)

// packs lists the packs lidza.json enables, started in this order.
func packs() []lidza.Pack {
	return []lidza.Pack{
		db.Pack(),
		auth.Pack(),
		jobs.Pack(),
		mail.Pack(),
		storage.Pack(),
	}
}
