import { expect, test } from '@playwright/test'

test('Calendar persists an all-day event, exports/imports ICS, and cancels a series', async ({ page }) => {
  const name = `Shared calendar ${Date.now()}`
  const title = `All-day planning ${Date.now()}`
  const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/New_York', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date())
  const tomorrow = new Date(`${today}T12:00:00Z`); tomorrow.setUTCDate(tomorrow.getUTCDate() + 1)
  const nextDate = tomorrow.toISOString().slice(0, 10)
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/app')
  await page.getByLabel('Email', { exact: true }).fill('owner-e2e@example.com')
  await page.getByLabel('Password', { exact: true }).fill('thura fixture maple lantern 4829')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Calendar', exact: true }).click()
  await page.getByLabel('New calendar name', { exact: true }).fill(name)
  await page.getByRole('button', { name: 'Create calendar', exact: true }).click()
  await expect(page.getByLabel('Calendar', { exact: true })).toContainText(name)
  await page.getByRole('button', { name: 'New event', exact: true }).click()
  await page.getByLabel('Event title', { exact: true }).fill(title)
  await page.getByLabel('All day', { exact: true }).check()
  await page.getByLabel('Start date', { exact: true }).fill(today)
  await page.getByLabel('End date (exclusive)', { exact: true }).fill(nextDate)
  await page.getByRole('button', { name: 'Save event', exact: true }).click()
  await expect(page.locator('.fc').getByText(title, { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Calendar', exact: true }).click()
  await page.getByLabel('Calendar', { exact: true }).selectOption({ label: `${name} · Shared` })
  await expect(page.locator('.fc').getByText(title, { exact: true })).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export ICS', exact: true }).click()
  const filePath = await (await download).path()
  expect(filePath).not.toBeNull()
  await page.getByLabel('New calendar name', { exact: true }).fill(`${name} imported`)
  await page.getByRole('button', { name: 'Create calendar', exact: true }).click()
  await expect(page.getByLabel('Calendar', { exact: true })).toHaveValue(/.+/)
  await page.getByLabel('Import ICS', { exact: true }).setInputFiles(filePath!)
  await expect(page.getByRole('status')).toContainText('Imported 1 records')
  await expect(page.locator('.fc').getByText(title, { exact: true })).toBeVisible()
  await page.locator('.fc').getByText(title, { exact: true }).click()
  await expect(page.getByLabel('All day', { exact: true })).toBeChecked()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Cancel series', exact: true }).click()
  await expect(page.locator('.fc').getByText(title, { exact: true })).toHaveCount(0)
  expect(errors).toEqual([])
})
