import { expect, test } from '@playwright/test'

test('Drive persists versions, downloads shares, revokes links, and restores trash', async ({ page, browser }) => {
  const name = `private-${Date.now()}.txt`
  await page.goto('/app')
  await page.getByLabel('Email', { exact: true }).fill('owner-e2e@example.com')
  await page.getByLabel('Password', { exact: true }).fill('thura fixture maple lantern 4829')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Drive', exact: true }).click()
  await page.getByLabel('Upload file', { exact: true }).setInputFiles({ name, mimeType: 'text/plain', buffer: Buffer.from('Original private bytes') })
  await expect(page.getByRole('status')).toHaveText('Upload complete')
  await expect(page.getByRole('heading', { name, exact: true })).toHaveCount(2)
  await page.reload()
  await page.getByRole('button', { name: 'Drive', exact: true }).click()
  await page.getByRole('button', { name, exact: true }).click()
  await page.getByLabel('Upload new version', { exact: true }).setInputFiles({ name, mimeType: 'text/plain', buffer: Buffer.from('Replacement bytes') })
  await expect(page.getByRole('button', { name: 'Download version 2', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Download version 1', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Create share link', exact: true }).click()
  const link = page.getByLabel('New share link', { exact: true })
  await expect(link).toHaveValue(/\/share#.+/)
  const context = await browser.newContext()
  const guest = await context.newPage()
  await guest.goto(await link.inputValue())
  const download = guest.waitForEvent('download')
  await guest.getByRole('button', { name: 'Download shared file', exact: true }).click()
  expect((await download).suggestedFilename()).toBe(name)
  await page.getByRole('button', { name: 'Revoke share', exact: true }).click()
  await expect(page.getByText('Revoked', { exact: false })).toBeVisible()
  await guest.getByRole('button', { name: 'Download shared file', exact: true }).click()
  await expect(guest.getByRole('alert')).toHaveText('share expired or revoked')
  await context.close()
  await page.getByRole('button', { name: `Move to trash ${name}`, exact: true }).click()
  await expect(page.getByRole('button', { name, exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Trash', exact: true }).click()
  await page.getByRole('button', { name: `Restore ${name}`, exact: true }).click()
  await page.getByRole('button', { name: 'All files', exact: true }).click()
  await expect(page.getByRole('button', { name: `Download ${name}`, exact: true })).toBeVisible()
})
