import { expect, test } from '@playwright/test'

test('cold pages defer workspace applications until sign-in and tab selection', async ({ page }) => {
  const scripts: string[] = []
  page.on('request', request => {
    if (request.resourceType() === 'script') scripts.push(new URL(request.url()).pathname)
  })
  const unopened = () => scripts.filter(path => /\/(?:Workspace|LiveWorkspace|Contacts|LiveDrive|LiveMail|LiveChat|LiveMeet|LiveCalendar|livekit-client|livekit-components)[-.]/.test(path))
  await page.goto('/')
  await expect(page.getByText('hello, world')).toBeVisible()
  await expect(page.locator('link[rel="modulepreload"][href*="/Home-"]')).toHaveCount(1)
  expect(unopened()).toEqual([])
  await page.getByRole('link', { name: 'Open Thura', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Sign in to Thura' })).toBeVisible()
  expect(unopened()).toEqual([])
  await page.getByLabel('Email', { exact: true }).fill('owner-e2e@example.com')
  await page.getByLabel('Password', { exact: true }).fill('thura fixture maple lantern 4829')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Inbox', exact: true })).toBeVisible()
  await expect.poll(() => scripts.some(path => /\/LiveMail[-.]/.test(path))).toBe(true)
  expect(scripts.filter(path => /\/(?:Contacts|LiveDrive|LiveChat|LiveMeet|LiveCalendar|livekit-client|livekit-components)[-.]/.test(path))).toEqual([])
  await page.getByRole('button', { name: 'Drive', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Drive', exact: true })).toBeVisible()
  await expect.poll(() => scripts.some(path => /\/LiveDrive[-.]/.test(path))).toBe(true)
  expect(scripts.filter(path => /\/(?:Contacts|LiveChat|LiveMeet|LiveCalendar|livekit-client|livekit-components)[-.]/.test(path))).toEqual([])
  await page.getByRole('button', { name: 'Contacts', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Contacts', exact: true })).toBeVisible()
  await expect.poll(() => scripts.some(path => /\/Contacts[-.]/.test(path))).toBe(true)
})

test('page metadata survives direct loads and client navigation without indexing private routes', async ({ page, request }) => {
  const response = await request.get('/share?token=synthetic-private-metadata-fixture')
  const html = await response.text()
  expect(html).toContain('<title>Shared file · Thura</title>')
  expect(html).toMatch(/name="robots"[^>]*content="noindex/)
  expect(html).not.toContain('synthetic-private-metadata-fixture')
  await page.goto('/')
  await expect(page).toHaveTitle('Thura')
  await expect(page.locator('meta[name="description"]')).toHaveAttribute('content', /Mail, contacts, files/)
  await page.getByRole('link', { name: 'Open Thura', exact: true }).click()
  await expect(page).toHaveTitle('Workspace · Thura')
  await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content', /noindex/)
  await page.goto('/about')
  await expect(page).toHaveTitle('About · Thura')
  await expect(page.locator('meta[name="description"]')).toHaveCount(1)
  await expect(page.locator('meta[name="robots"]')).toHaveCount(0)
  await expect(page.locator('script:not([type="application/ld+json"])')).toHaveCount(0)
  await expect(page.locator('link[rel="modulepreload"]')).toHaveCount(0)
})
