-- Code generated by lidza gen from schema.lidza. DO NOT EDIT.
-- The current schema in full; migrations in db/migrations carry the changes.

CREATE TYPE workspace_role AS ENUM ('owner', 'admin', 'member');

CREATE TABLE workspace (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(120) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE contact (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  name varchar(200) NOT NULL,
  email varchar(254) NOT NULL,
  company varchar(200) NOT NULL DEFAULT '',
  phone varchar(80) NOT NULL DEFAULT '',
  favorite boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX contact_workspace_id_idx ON contact (workspace_id);

CREATE TABLE invitation (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  email varchar(254) NOT NULL,
  role workspace_role NOT NULL,
  token_hash text NOT NULL UNIQUE,
  invited_by text NOT NULL,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX invitation_workspace_id_idx ON invitation (workspace_id);

CREATE TABLE auth_session (
  id text PRIMARY KEY,
  subject text NOT NULL,
  refresh_hash text NOT NULL UNIQUE,
  prev_refresh_hash text,
  rotated_at timestamptz,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  remember boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_session_subject_idx ON auth_session (subject);

CREATE TABLE auth_token (
  id text PRIMARY KEY,
  purpose text NOT NULL,
  subject text NOT NULL,
  hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_token_purpose_idx ON auth_token (purpose);
CREATE INDEX auth_token_subject_idx ON auth_token (subject);

CREATE TABLE auth_account (
  subject text PRIMARY KEY,
  label text,
  disabled_at timestamptz,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth_user (
  subject text PRIMARY KEY,
  email text UNIQUE,
  name text,
  password_hash text,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth_identity (
  id text PRIMARY KEY,
  provider text NOT NULL,
  provider_subject text NOT NULL,
  subject text NOT NULL,
  email text,
  name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_identity_provider_idx ON auth_identity (provider);
CREATE INDEX auth_identity_subject_idx ON auth_identity (subject);

CREATE TABLE auth_connection (
  id text PRIMARY KEY,
  owner text NOT NULL,
  provider text NOT NULL,
  subject text NOT NULL,
  login text NOT NULL DEFAULT '',
  scopes text NOT NULL DEFAULT '',
  token_type text NOT NULL DEFAULT '',
  access_sealed text NOT NULL,
  refresh_sealed text NOT NULL DEFAULT '',
  expires_at timestamptz,
  reconnect boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX auth_connection_owner_provider_key ON auth_connection (owner, provider);

CREATE TABLE auth_member (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject text NOT NULL,
  scope text NOT NULL DEFAULT '',
  role text NOT NULL,
  granted_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX auth_member_subject_scope_role_key ON auth_member (subject, scope, role);
CREATE INDEX auth_member_scope_role_idx ON auth_member (scope, role);

CREATE TABLE job (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind text NOT NULL,
  payload jsonb NOT NULL,
  state text NOT NULL DEFAULT 'pending',
  run_at timestamptz NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 5,
  locked_at timestamptz,
  finished_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  unique_key text
);
CREATE INDEX job_state_run_at_idx ON job (state, run_at);
CREATE UNIQUE INDEX job_kind_unique_key_key ON job (kind, unique_key);

CREATE TABLE job_schedule (
  kind text PRIMARY KEY,
  spec text NOT NULL,
  next_run_at timestamptz NOT NULL,
  last_run_at timestamptz,
  last_job_id uuid,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE mail_message (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient text NOT NULL,
  from_address text,
  reply_to text,
  headers jsonb,
  cc text[],
  bcc text[],
  attachments jsonb,
  subject text NOT NULL,
  text text,
  html text,
  template text,
  status text NOT NULL,
  provider_id text,
  error text,
  attempts integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz
);
CREATE INDEX mail_message_recipient_idx ON mail_message (recipient);
CREATE INDEX mail_message_status_idx ON mail_message (status);
CREATE INDEX mail_message_created_at_idx ON mail_message (created_at);

