-- Code generated by lidza gen from schema.lidza. DO NOT EDIT.
-- The current schema in full; migrations in db/migrations carry the changes.

CREATE TYPE workspace_role AS ENUM ('owner', 'admin', 'member');

CREATE TYPE mail_folder AS ENUM ('inbox', 'drafts', 'sent', 'archive', 'trash', 'spam');

CREATE TYPE attendance AS ENUM ('needsaction', 'accepted', 'tentative', 'declined');

CREATE TABLE workspace (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(120) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE contact (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  name varchar(200) NOT NULL,
  email varchar(254) NOT NULL,
  company varchar(200) NOT NULL DEFAULT '',
  phone varchar(80) NOT NULL DEFAULT '',
  favorite boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX contact_workspace_id_idx ON contact (workspace_id);

CREATE TABLE invitation (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  email varchar(254) NOT NULL,
  role workspace_role NOT NULL,
  token_hash text NOT NULL UNIQUE,
  invited_by text NOT NULL,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX invitation_workspace_id_idx ON invitation (workspace_id);

CREATE TABLE drive_file (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  folder_id uuid,
  name varchar(200) NOT NULL,
  content_type text NOT NULL,
  size integer NOT NULL,
  current_version integer NOT NULL DEFAULT 1,
  trashed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX drive_file_workspace_id_idx ON drive_file (workspace_id);

CREATE TABLE drive_preview (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  file_id uuid NOT NULL UNIQUE REFERENCES drive_file(id),
  version integer NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  object_key text NOT NULL DEFAULT '',
  checksum text NOT NULL DEFAULT '',
  content_type text NOT NULL DEFAULT '',
  width integer NOT NULL DEFAULT 0,
  height integer NOT NULL DEFAULT 0,
  truncated boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now(),
  job_id text NOT NULL DEFAULT ''
);

CREATE TABLE mailbox (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  name varchar(120) NOT NULL,
  address varchar(254) NOT NULL,
  config_prefix varchar(100) NOT NULL,
  signature text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX mailbox_workspace_id_idx ON mailbox (workspace_id);

CREATE TABLE mail_item (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  mailbox_id uuid NOT NULL REFERENCES mailbox(id),
  author_id text NOT NULL,
  folder mail_folder NOT NULL,
  from_address text NOT NULL DEFAULT '',
  to_address text NOT NULL DEFAULT '',
  cc text NOT NULL DEFAULT '',
  bcc text NOT NULL DEFAULT '',
  subject text NOT NULL DEFAULT '',
  text_body text NOT NULL DEFAULT '',
  html_body text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'draft',
  starred boolean NOT NULL DEFAULT false,
  unread boolean NOT NULL DEFAULT false,
  provider_id text NOT NULL DEFAULT '',
  raw_key text NOT NULL DEFAULT '',
  external_id text,
  thread_id text NOT NULL DEFAULT '',
  message_id text NOT NULL DEFAULT '',
  in_reply_to text NOT NULL DEFAULT '',
  references_header text NOT NULL DEFAULT '',
  send_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX mail_item_mailbox_id_idx ON mail_item (mailbox_id);
CREATE UNIQUE INDEX mail_item_mailbox_id_external_id_key ON mail_item (mailbox_id, external_id);

CREATE TABLE mail_attachment (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL REFERENCES mail_item(id),
  name text NOT NULL,
  content_type text NOT NULL,
  size integer NOT NULL,
  object_key text NOT NULL,
  content_id text NOT NULL DEFAULT ''
);
CREATE INDEX mail_attachment_item_id_idx ON mail_attachment (item_id);

CREATE TABLE auth_session (
  id text PRIMARY KEY,
  subject text NOT NULL,
  refresh_hash text NOT NULL UNIQUE,
  prev_refresh_hash text,
  rotated_at timestamptz,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  remember boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_session_subject_idx ON auth_session (subject);

CREATE TABLE auth_token (
  id text PRIMARY KEY,
  purpose text NOT NULL,
  subject text NOT NULL,
  hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_token_purpose_idx ON auth_token (purpose);
CREATE INDEX auth_token_subject_idx ON auth_token (subject);

CREATE TABLE auth_account (
  subject text PRIMARY KEY,
  label text,
  disabled_at timestamptz,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth_user (
  subject text PRIMARY KEY,
  email text UNIQUE,
  name text,
  password_hash text,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth_identity (
  id text PRIMARY KEY,
  provider text NOT NULL,
  provider_subject text NOT NULL,
  subject text NOT NULL,
  email text,
  name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_identity_provider_idx ON auth_identity (provider);
CREATE INDEX auth_identity_subject_idx ON auth_identity (subject);

CREATE TABLE auth_connection (
  id text PRIMARY KEY,
  owner text NOT NULL,
  provider text NOT NULL,
  subject text NOT NULL,
  login text NOT NULL DEFAULT '',
  scopes text NOT NULL DEFAULT '',
  token_type text NOT NULL DEFAULT '',
  access_sealed text NOT NULL,
  refresh_sealed text NOT NULL DEFAULT '',
  expires_at timestamptz,
  reconnect boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX auth_connection_owner_provider_key ON auth_connection (owner, provider);

CREATE TABLE auth_member (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject text NOT NULL,
  scope text NOT NULL DEFAULT '',
  role text NOT NULL,
  granted_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX auth_member_subject_scope_role_key ON auth_member (subject, scope, role);
CREATE INDEX auth_member_scope_role_idx ON auth_member (scope, role);

CREATE TABLE job (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind text NOT NULL,
  payload jsonb NOT NULL,
  state text NOT NULL DEFAULT 'pending',
  run_at timestamptz NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 5,
  locked_at timestamptz,
  finished_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  unique_key text
);
CREATE INDEX job_state_run_at_idx ON job (state, run_at);
CREATE UNIQUE INDEX job_kind_unique_key_key ON job (kind, unique_key);

CREATE TABLE job_schedule (
  kind text PRIMARY KEY,
  spec text NOT NULL,
  next_run_at timestamptz NOT NULL,
  last_run_at timestamptz,
  last_job_id uuid,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE mail_message (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient text NOT NULL,
  from_address text,
  reply_to text,
  headers jsonb,
  cc text[],
  bcc text[],
  attachments jsonb,
  subject text NOT NULL,
  text text,
  html text,
  template text,
  status text NOT NULL,
  provider_id text,
  error text,
  attempts integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz
);
CREATE INDEX mail_message_recipient_idx ON mail_message (recipient);
CREATE INDEX mail_message_status_idx ON mail_message (status);
CREATE INDEX mail_message_created_at_idx ON mail_message (created_at);

CREATE TABLE drive_folder (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  parent_id uuid,
  name varchar(200) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX drive_folder_workspace_id_idx ON drive_folder (workspace_id);

CREATE TABLE file_version (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  file_id uuid NOT NULL REFERENCES drive_file(id),
  number integer NOT NULL,
  object_key text NOT NULL,
  checksum text NOT NULL,
  size integer NOT NULL,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX file_version_file_id_idx ON file_version (file_id);
CREATE INDEX file_version_object_key_idx ON file_version (object_key);
CREATE UNIQUE INDEX file_version_file_id_number_key ON file_version (file_id, number);

CREATE TABLE upload_session (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  subject text NOT NULL,
  file_id uuid,
  folder_id uuid,
  name text NOT NULL,
  content_type text NOT NULL,
  expected_size integer NOT NULL,
  base_version integer NOT NULL,
  expires_at timestamptz NOT NULL,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX upload_session_workspace_id_idx ON upload_session (workspace_id);

CREATE TABLE upload_chunk (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES upload_session(id),
  number integer NOT NULL,
  size integer NOT NULL,
  checksum text NOT NULL,
  object_key text NOT NULL
);
CREATE INDEX upload_chunk_session_id_idx ON upload_chunk (session_id);
CREATE INDEX upload_chunk_object_key_idx ON upload_chunk (object_key);
CREATE UNIQUE INDEX upload_chunk_session_id_number_key ON upload_chunk (session_id, number);

CREATE TABLE share_grant (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  file_id uuid NOT NULL REFERENCES drive_file(id),
  token_hash text NOT NULL UNIQUE,
  target_email text NOT NULL DEFAULT '',
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX share_grant_file_id_idx ON share_grant (file_id);

CREATE TABLE office_session (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  file_id uuid NOT NULL REFERENCES drive_file(id),
  subject text NOT NULL,
  source_version integer NOT NULL,
  base_version integer NOT NULL,
  document_key text NOT NULL,
  last_checksum text NOT NULL DEFAULT '',
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX office_session_file_id_idx ON office_session (file_id);

CREATE TABLE calendar (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  name varchar(200) NOT NULL,
  color text NOT NULL,
  owner_subject text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX calendar_workspace_id_idx ON calendar (workspace_id);

CREATE TABLE meeting (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  request_id uuid NOT NULL,
  name varchar(200) NOT NULL,
  created_by text NOT NULL,
  ended_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX meeting_workspace_id_idx ON meeting (workspace_id);
CREATE UNIQUE INDEX meeting_workspace_id_request_id_key ON meeting (workspace_id, request_id);

CREATE TABLE calendar_event (
  meeting_id uuid REFERENCES meeting(id),
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  calendar_id uuid NOT NULL REFERENCES calendar(id),
  uid text NOT NULL,
  organizer text NOT NULL,
  title varchar(500) NOT NULL,
  description text NOT NULL DEFAULT '',
  location text NOT NULL DEFAULT '',
  all_day boolean NOT NULL,
  start_date text NOT NULL DEFAULT '',
  end_date text NOT NULL DEFAULT '',
  starts_at timestamptz,
  ends_at timestamptz,
  time_zone text NOT NULL,
  rrule text NOT NULL DEFAULT '',
  sequence integer NOT NULL DEFAULT 0,
  cancelled boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX calendar_event_calendar_id_idx ON calendar_event (calendar_id);
CREATE UNIQUE INDEX calendar_event_calendar_id_uid_key ON calendar_event (calendar_id, uid);

CREATE TABLE event_exception (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES calendar_event(id),
  instance_key text NOT NULL,
  cancelled boolean NOT NULL,
  title text,
  starts_at timestamptz,
  ends_at timestamptz,
  start_date text,
  end_date text
);
CREATE INDEX event_exception_event_id_idx ON event_exception (event_id);
CREATE UNIQUE INDEX event_exception_event_id_instance_key_key ON event_exception (event_id, instance_key);

CREATE TABLE event_attendee (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES calendar_event(id),
  email text NOT NULL,
  response attendance NOT NULL DEFAULT 'needsaction',
  response_sequence integer NOT NULL DEFAULT 0
);
CREATE INDEX event_attendee_event_id_idx ON event_attendee (event_id);
CREATE UNIQUE INDEX event_attendee_event_id_email_key ON event_attendee (event_id, email);

CREATE TABLE calendar_reply_grant (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  attendee_id uuid NOT NULL REFERENCES event_attendee(id),
  token_hash text NOT NULL UNIQUE,
  sequence integer NOT NULL,
  instance_key text NOT NULL DEFAULT '',
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX calendar_reply_grant_attendee_id_idx ON calendar_reply_grant (attendee_id);

CREATE TABLE calendar_dispatch (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES calendar_event(id),
  sequence integer NOT NULL,
  instance_key text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX calendar_dispatch_event_id_idx ON calendar_dispatch (event_id);
CREATE UNIQUE INDEX calendar_dispatch_event_id_sequence_instance_key_key ON calendar_dispatch (event_id, sequence, instance_key);

CREATE TABLE calendar_reminder (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES calendar_event(id),
  subject text NOT NULL,
  minutes_before integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX calendar_reminder_event_id_idx ON calendar_reminder (event_id);
CREATE UNIQUE INDEX calendar_reminder_event_id_subject_key ON calendar_reminder (event_id, subject);

CREATE TABLE reminder_notice (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES calendar_event(id),
  subject text NOT NULL,
  sequence integer NOT NULL,
  instance_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reminder_notice_event_id_idx ON reminder_notice (event_id);
CREATE UNIQUE INDEX reminder_notice_event_id_subject_sequence_instance_key_key ON reminder_notice (event_id, subject, sequence, instance_key);

CREATE TABLE chat_room (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  matrix_room_id text NOT NULL UNIQUE,
  request_id uuid NOT NULL,
  name varchar(200) NOT NULL,
  direct boolean NOT NULL DEFAULT false,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX chat_room_workspace_id_idx ON chat_room (workspace_id);
CREATE UNIQUE INDEX chat_room_workspace_id_request_id_key ON chat_room (workspace_id, request_id);

CREATE TABLE chat_participant (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id uuid NOT NULL REFERENCES chat_room(id),
  subject text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX chat_participant_room_id_idx ON chat_participant (room_id);
CREATE UNIQUE INDEX chat_participant_room_id_subject_key ON chat_participant (room_id, subject);

CREATE TABLE meeting_participant (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL REFERENCES meeting(id),
  subject text NOT NULL,
  token_expires_at timestamptz NOT NULL,
  joined boolean NOT NULL DEFAULT false,
  session_id text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX meeting_participant_meeting_id_idx ON meeting_participant (meeting_id);
CREATE UNIQUE INDEX meeting_participant_meeting_id_subject_key ON meeting_participant (meeting_id, subject);

CREATE TABLE meeting_webhook (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id text NOT NULL UNIQUE,
  checksum text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE mail_label (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  mailbox_id uuid NOT NULL REFERENCES mailbox(id),
  name varchar(40) NOT NULL
);
CREATE INDEX mail_label_mailbox_id_idx ON mail_label (mailbox_id);
CREATE UNIQUE INDEX mail_label_mailbox_id_name_key ON mail_label (mailbox_id, name);

CREATE TABLE mail_tag (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL REFERENCES mail_item(id),
  label_id uuid NOT NULL REFERENCES mail_label(id)
);
CREATE INDEX mail_tag_item_id_idx ON mail_tag (item_id);
CREATE INDEX mail_tag_label_id_idx ON mail_tag (label_id);
CREATE UNIQUE INDEX mail_tag_item_id_label_id_key ON mail_tag (item_id, label_id);

CREATE TABLE audit_event (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  at timestamptz NOT NULL DEFAULT now(),
  actor text NOT NULL,
  action text NOT NULL,
  resource text NOT NULL DEFAULT '',
  scope text NOT NULL DEFAULT '',
  outcome text NOT NULL,
  request_id text NOT NULL DEFAULT '',
  meta jsonb NOT NULL
);
CREATE INDEX audit_event_at_id_idx ON audit_event (at, id);
CREATE INDEX audit_event_actor_at_idx ON audit_event (actor, at);
CREATE INDEX audit_event_scope_at_idx ON audit_event (scope, at);

CREATE TABLE smip_binding (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  peer text NOT NULL,
  stream text NOT NULL,
  sender text NOT NULL,
  recipient text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX smip_binding_workspace_id_idx ON smip_binding (workspace_id);
CREATE UNIQUE INDEX smip_binding_peer_stream_recipient_key ON smip_binding (peer, stream, recipient);

CREATE TABLE smip_inbox (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  binding_id uuid NOT NULL REFERENCES smip_binding(id),
  origin text NOT NULL,
  message_id text NOT NULL,
  digest text NOT NULL,
  record text NOT NULL,
  origin_key text NOT NULL,
  receipt_key text NOT NULL,
  sender text NOT NULL DEFAULT '',
  recipient text NOT NULL DEFAULT '',
  stream text NOT NULL DEFAULT '',
  body text NOT NULL DEFAULT '',
  name text NOT NULL DEFAULT '',
  kind text NOT NULL,
  size integer NOT NULL,
  imported_file_id uuid,
  imported_at timestamptz,
  accepted_at timestamptz NOT NULL
);
CREATE INDEX smip_inbox_workspace_id_idx ON smip_inbox (workspace_id);
CREATE UNIQUE INDEX smip_inbox_origin_message_id_key ON smip_inbox (origin, message_id);

CREATE TABLE smip_outbox (
  id uuid PRIMARY KEY,
  origin text NOT NULL DEFAULT '',
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  binding_id uuid NOT NULL REFERENCES smip_binding(id),
  subject text NOT NULL,
  packet text NOT NULL,
  origin_key text NOT NULL,
  receipt text NOT NULL DEFAULT '',
  receipt_key text NOT NULL DEFAULT '',
  kind text NOT NULL,
  body text NOT NULL,
  name text NOT NULL,
  size integer NOT NULL,
  source_file_id uuid,
  state text NOT NULL DEFAULT 'pending',
  reason text NOT NULL DEFAULT '',
  attempts integer NOT NULL DEFAULT 0,
  attempt_id text NOT NULL DEFAULT '',
  last_status integer NOT NULL DEFAULT 0,
  next_attempt timestamptz NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE INDEX smip_outbox_workspace_id_idx ON smip_outbox (workspace_id);

CREATE TABLE server_setup (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject text NOT NULL DEFAULT '',
  workspace_id uuid,
  revision integer NOT NULL DEFAULT 0,
  published_revision integer NOT NULL DEFAULT 0,
  draft text NOT NULL DEFAULT '',
  published text NOT NULL DEFAULT '',
  step text NOT NULL DEFAULT 'server',
  published_at timestamptz
);

CREATE TABLE auth_owner_claim (
  id text PRIMARY KEY,
  token_hash text NOT NULL,
  subject text,
  claimed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

