// Code generated by lidza gen from schema.lidza. DO NOT EDIT.

package schema

import (
	"encoding/json"
	"github.com/agim/lidza/pkg/validate"
	"time"
)

// WorkspaceRole is the WorkspaceRole enum.
type WorkspaceRole string

const (
	WorkspaceRoleOwner  WorkspaceRole = "owner"
	WorkspaceRoleAdmin  WorkspaceRole = "admin"
	WorkspaceRoleMember WorkspaceRole = "member"
)

// WorkspaceRoleValues lists every WorkspaceRole.
var WorkspaceRoleValues = []WorkspaceRole{WorkspaceRoleOwner, WorkspaceRoleAdmin, WorkspaceRoleMember}

// Valid reports whether v is one of the WorkspaceRole values.
func (v WorkspaceRole) Valid() bool {
	for _, x := range WorkspaceRoleValues {
		if v == x {
			return true
		}
	}
	return false
}

// MailFolder is the MailFolder enum.
type MailFolder string

const (
	MailFolderInbox   MailFolder = "inbox"
	MailFolderDrafts  MailFolder = "drafts"
	MailFolderSent    MailFolder = "sent"
	MailFolderArchive MailFolder = "archive"
	MailFolderTrash   MailFolder = "trash"
	MailFolderSpam    MailFolder = "spam"
)

// MailFolderValues lists every MailFolder.
var MailFolderValues = []MailFolder{MailFolderInbox, MailFolderDrafts, MailFolderSent, MailFolderArchive, MailFolderTrash, MailFolderSpam}

// Valid reports whether v is one of the MailFolder values.
func (v MailFolder) Valid() bool {
	for _, x := range MailFolderValues {
		if v == x {
			return true
		}
	}
	return false
}

// Attendance is the Attendance enum.
type Attendance string

const (
	AttendanceNeedsaction Attendance = "needsaction"
	AttendanceAccepted    Attendance = "accepted"
	AttendanceTentative   Attendance = "tentative"
	AttendanceDeclined    Attendance = "declined"
)

// AttendanceValues lists every Attendance.
var AttendanceValues = []Attendance{AttendanceNeedsaction, AttendanceAccepted, AttendanceTentative, AttendanceDeclined}

// Valid reports whether v is one of the Attendance values.
func (v Attendance) Valid() bool {
	for _, x := range AttendanceValues {
		if v == x {
			return true
		}
	}
	return false
}

// Workspace is a row of the workspace table.
type Workspace struct {
	ID        string    `json:"id" db:"id"`
	Name      string    `json:"name" db:"name"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of Workspace from schema.lidza.
func (v Workspace) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 120 {
		errs.Add("name", "max", "at most 120 character(s)")
	}
	return errs.Result()
}

// Contact is a row of the contact table.
type Contact struct {
	ID          string    `json:"id" db:"id"`
	WorkspaceID string    `json:"workspaceId" db:"workspace_id"`
	Name        string    `json:"name" db:"name"`
	Email       string    `json:"email" db:"email"`
	Company     string    `json:"company" db:"company"`
	Phone       string    `json:"phone" db:"phone"`
	Favorite    bool      `json:"favorite" db:"favorite"`
	CreatedAt   time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of Contact from schema.lidza.
func (v Contact) Validate() error {
	var errs validate.Errors
	if v.WorkspaceID == "" {
		errs.Add("workspaceId", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if len(v.Email) > 254 {
		errs.Add("email", "max", "at most 254 character(s)")
	}
	if v.Email != "" && !validate.Email(v.Email) {
		errs.Add("email", "email", "not an email address")
	}
	if v.Company == "" {
		errs.Add("company", "required", "required")
	}
	if len(v.Company) > 200 {
		errs.Add("company", "max", "at most 200 character(s)")
	}
	if v.Phone == "" {
		errs.Add("phone", "required", "required")
	}
	if len(v.Phone) > 80 {
		errs.Add("phone", "max", "at most 80 character(s)")
	}
	return errs.Result()
}

// Invitation is a row of the invitation table.
type Invitation struct {
	ID          string        `json:"id" db:"id"`
	WorkspaceID string        `json:"workspaceId" db:"workspace_id"`
	Email       string        `json:"email" db:"email"`
	Role        WorkspaceRole `json:"role" db:"role"`
	TokenHash   string        `json:"tokenHash" db:"token_hash"`
	InvitedBy   string        `json:"invitedBy" db:"invited_by"`
	ExpiresAt   time.Time     `json:"expiresAt" db:"expires_at"`
	AcceptedAt  *time.Time    `json:"acceptedAt" db:"accepted_at"`
	RevokedAt   *time.Time    `json:"revokedAt" db:"revoked_at"`
	CreatedAt   time.Time     `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of Invitation from schema.lidza.
func (v Invitation) Validate() error {
	var errs validate.Errors
	if v.WorkspaceID == "" {
		errs.Add("workspaceId", "required", "required")
	}
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if len(v.Email) > 254 {
		errs.Add("email", "max", "at most 254 character(s)")
	}
	if v.Email != "" && !validate.Email(v.Email) {
		errs.Add("email", "email", "not an email address")
	}
	if v.Role == "" {
		errs.Add("role", "required", "required")
	}
	if v.Role != "" && !v.Role.Valid() {
		errs.Add("role", "enum", "unknown WorkspaceRole value")
	}
	if v.TokenHash == "" {
		errs.Add("tokenHash", "required", "required")
	}
	if v.InvitedBy == "" {
		errs.Add("invitedBy", "required", "required")
	}
	return errs.Result()
}

// Mailbox is a row of the mailbox table.
type Mailbox struct {
	ID           string    `json:"id" db:"id"`
	WorkspaceID  string    `json:"workspaceId" db:"workspace_id"`
	Name         string    `json:"name" db:"name"`
	Address      string    `json:"address" db:"address"`
	ConfigPrefix string    `json:"configPrefix" db:"config_prefix"`
	CreatedAt    time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of Mailbox from schema.lidza.
func (v Mailbox) Validate() error {
	var errs validate.Errors
	if v.WorkspaceID == "" {
		errs.Add("workspaceId", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) > 120 {
		errs.Add("name", "max", "at most 120 character(s)")
	}
	if v.Address == "" {
		errs.Add("address", "required", "required")
	}
	if len(v.Address) > 254 {
		errs.Add("address", "max", "at most 254 character(s)")
	}
	if v.Address != "" && !validate.Email(v.Address) {
		errs.Add("address", "email", "not an email address")
	}
	if v.ConfigPrefix == "" {
		errs.Add("configPrefix", "required", "required")
	}
	if len(v.ConfigPrefix) > 100 {
		errs.Add("configPrefix", "max", "at most 100 character(s)")
	}
	return errs.Result()
}

// MailItem is a row of the mail_item table.
type MailItem struct {
	ID          string     `json:"id" db:"id"`
	MailboxID   string     `json:"mailboxId" db:"mailbox_id"`
	AuthorID    string     `json:"authorId" db:"author_id"`
	Folder      MailFolder `json:"folder" db:"folder"`
	FromAddress string     `json:"fromAddress" db:"from_address"`
	ToAddress   string     `json:"toAddress" db:"to_address"`
	Cc          string     `json:"cc" db:"cc"`
	Bcc         string     `json:"bcc" db:"bcc"`
	Subject     string     `json:"subject" db:"subject"`
	TextBody    string     `json:"textBody" db:"text_body"`
	HTMLBody    string     `json:"htmlBody" db:"html_body"`
	Status      string     `json:"status" db:"status"`
	Starred     bool       `json:"starred" db:"starred"`
	Unread      bool       `json:"unread" db:"unread"`
	ProviderID  string     `json:"providerId" db:"provider_id"`
	RawKey      string     `json:"rawKey" db:"raw_key"`
	ExternalID  *string    `json:"externalId" db:"external_id"`
	ThreadID    string     `json:"threadId" db:"thread_id"`
	SendAt      *time.Time `json:"sendAt" db:"send_at"`
	CreatedAt   time.Time  `json:"createdAt" db:"created_at"`
	UpdatedAt   time.Time  `json:"updatedAt" db:"updated_at"`
}

// Validate applies the rules of MailItem from schema.lidza.
func (v MailItem) Validate() error {
	var errs validate.Errors
	if v.MailboxID == "" {
		errs.Add("mailboxId", "required", "required")
	}
	if v.AuthorID == "" {
		errs.Add("authorId", "required", "required")
	}
	if v.Folder == "" {
		errs.Add("folder", "required", "required")
	}
	if v.Folder != "" && !v.Folder.Valid() {
		errs.Add("folder", "enum", "unknown MailFolder value")
	}
	if v.FromAddress == "" {
		errs.Add("fromAddress", "required", "required")
	}
	if v.ToAddress == "" {
		errs.Add("toAddress", "required", "required")
	}
	if v.Cc == "" {
		errs.Add("cc", "required", "required")
	}
	if v.Bcc == "" {
		errs.Add("bcc", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.TextBody == "" {
		errs.Add("textBody", "required", "required")
	}
	if v.HTMLBody == "" {
		errs.Add("htmlBody", "required", "required")
	}
	if v.Status == "" {
		errs.Add("status", "required", "required")
	}
	if v.ProviderID == "" {
		errs.Add("providerId", "required", "required")
	}
	if v.RawKey == "" {
		errs.Add("rawKey", "required", "required")
	}
	if v.ThreadID == "" {
		errs.Add("threadId", "required", "required")
	}
	return errs.Result()
}

// MailAttachment is a row of the mail_attachment table.
type MailAttachment struct {
	ID          string `json:"id" db:"id"`
	ItemID      string `json:"itemId" db:"item_id"`
	Name        string `json:"name" db:"name"`
	ContentType string `json:"contentType" db:"content_type"`
	Size        int    `json:"size" db:"size"`
	ObjectKey   string `json:"objectKey" db:"object_key"`
	ContentID   string `json:"contentId" db:"content_id"`
}

// Validate applies the rules of MailAttachment from schema.lidza.
func (v MailAttachment) Validate() error {
	var errs validate.Errors
	if v.ItemID == "" {
		errs.Add("itemId", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if v.ContentType == "" {
		errs.Add("contentType", "required", "required")
	}
	if v.ObjectKey == "" {
		errs.Add("objectKey", "required", "required")
	}
	if v.ContentID == "" {
		errs.Add("contentId", "required", "required")
	}
	return errs.Result()
}

// AuthSession is a row of the auth_session table.
type AuthSession struct {
	ID              string     `json:"id" db:"id"`
	Subject         string     `json:"subject" db:"subject"`
	RefreshHash     string     `json:"refreshHash" db:"refresh_hash"`
	PrevRefreshHash *string    `json:"prevRefreshHash" db:"prev_refresh_hash"`
	RotatedAt       *time.Time `json:"rotatedAt" db:"rotated_at"`
	ExpiresAt       time.Time  `json:"expiresAt" db:"expires_at"`
	RevokedAt       *time.Time `json:"revokedAt" db:"revoked_at"`
	Remember        bool       `json:"remember" db:"remember"`
	CreatedAt       time.Time  `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of AuthSession from schema.lidza.
func (v AuthSession) Validate() error {
	var errs validate.Errors
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.RefreshHash == "" {
		errs.Add("refreshHash", "required", "required")
	}
	return errs.Result()
}

// AuthToken is a row of the auth_token table.
type AuthToken struct {
	ID        string     `json:"id" db:"id"`
	Purpose   string     `json:"purpose" db:"purpose"`
	Subject   string     `json:"subject" db:"subject"`
	Hash      string     `json:"hash" db:"hash"`
	ExpiresAt time.Time  `json:"expiresAt" db:"expires_at"`
	UsedAt    *time.Time `json:"usedAt" db:"used_at"`
	CreatedAt time.Time  `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of AuthToken from schema.lidza.
func (v AuthToken) Validate() error {
	var errs validate.Errors
	if v.Purpose == "" {
		errs.Add("purpose", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.Hash == "" {
		errs.Add("hash", "required", "required")
	}
	return errs.Result()
}

// AuthAccount is a row of the auth_account table.
type AuthAccount struct {
	Subject     string     `json:"subject" db:"subject"`
	Label       *string    `json:"label" db:"label"`
	DisabledAt  *time.Time `json:"disabledAt" db:"disabled_at"`
	FirstSeenAt time.Time  `json:"firstSeenAt" db:"first_seen_at"`
	LastSeenAt  time.Time  `json:"lastSeenAt" db:"last_seen_at"`
}

// Validate applies the rules of AuthAccount from schema.lidza.
func (v AuthAccount) Validate() error {
	var errs validate.Errors
	return errs.Result()
}

// AuthUser is a row of the auth_user table.
type AuthUser struct {
	Subject      string     `json:"subject" db:"subject"`
	Email        *string    `json:"email" db:"email"`
	Name         *string    `json:"name" db:"name"`
	PasswordHash *string    `json:"passwordHash" db:"password_hash"`
	VerifiedAt   *time.Time `json:"verifiedAt" db:"verified_at"`
	CreatedAt    time.Time  `json:"createdAt" db:"created_at"`
	UpdatedAt    time.Time  `json:"updatedAt" db:"updated_at"`
}

// Validate applies the rules of AuthUser from schema.lidza.
func (v AuthUser) Validate() error {
	var errs validate.Errors
	return errs.Result()
}

// AuthIdentity is a row of the auth_identity table.
type AuthIdentity struct {
	ID              string    `json:"id" db:"id"`
	Provider        string    `json:"provider" db:"provider"`
	ProviderSubject string    `json:"providerSubject" db:"provider_subject"`
	Subject         string    `json:"subject" db:"subject"`
	Email           *string   `json:"email" db:"email"`
	Name            *string   `json:"name" db:"name"`
	CreatedAt       time.Time `json:"createdAt" db:"created_at"`
	LastUsedAt      time.Time `json:"lastUsedAt" db:"last_used_at"`
}

// Validate applies the rules of AuthIdentity from schema.lidza.
func (v AuthIdentity) Validate() error {
	var errs validate.Errors
	if v.Provider == "" {
		errs.Add("provider", "required", "required")
	}
	if v.ProviderSubject == "" {
		errs.Add("providerSubject", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	return errs.Result()
}

// AuthConnection is a row of the auth_connection table.
type AuthConnection struct {
	ID            string     `json:"id" db:"id"`
	Owner         string     `json:"owner" db:"owner"`
	Provider      string     `json:"provider" db:"provider"`
	Subject       string     `json:"subject" db:"subject"`
	Login         string     `json:"login" db:"login"`
	Scopes        string     `json:"scopes" db:"scopes"`
	TokenType     string     `json:"tokenType" db:"token_type"`
	AccessSealed  string     `json:"accessSealed" db:"access_sealed"`
	RefreshSealed string     `json:"refreshSealed" db:"refresh_sealed"`
	ExpiresAt     *time.Time `json:"expiresAt" db:"expires_at"`
	Reconnect     bool       `json:"reconnect" db:"reconnect"`
	CreatedAt     time.Time  `json:"createdAt" db:"created_at"`
	UpdatedAt     time.Time  `json:"updatedAt" db:"updated_at"`
}

// Validate applies the rules of AuthConnection from schema.lidza.
func (v AuthConnection) Validate() error {
	var errs validate.Errors
	if v.Owner == "" {
		errs.Add("owner", "required", "required")
	}
	if v.Provider == "" {
		errs.Add("provider", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.Login == "" {
		errs.Add("login", "required", "required")
	}
	if v.Scopes == "" {
		errs.Add("scopes", "required", "required")
	}
	if v.TokenType == "" {
		errs.Add("tokenType", "required", "required")
	}
	if v.AccessSealed == "" {
		errs.Add("accessSealed", "required", "required")
	}
	if v.RefreshSealed == "" {
		errs.Add("refreshSealed", "required", "required")
	}
	return errs.Result()
}

// AuthMember is a row of the auth_member table.
type AuthMember struct {
	ID        string    `json:"id" db:"id"`
	Subject   string    `json:"subject" db:"subject"`
	Scope     string    `json:"scope" db:"scope"`
	Role      string    `json:"role" db:"role"`
	GrantedBy *string   `json:"grantedBy" db:"granted_by"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of AuthMember from schema.lidza.
func (v AuthMember) Validate() error {
	var errs validate.Errors
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.Scope == "" {
		errs.Add("scope", "required", "required")
	}
	if v.Role == "" {
		errs.Add("role", "required", "required")
	}
	return errs.Result()
}

// Job is a row of the job table.
type Job struct {
	ID          string          `json:"id" db:"id"`
	Kind        string          `json:"kind" db:"kind"`
	Payload     json.RawMessage `json:"payload" db:"payload"`
	State       string          `json:"state" db:"state"`
	RunAt       time.Time       `json:"runAt" db:"run_at"`
	Attempts    int             `json:"attempts" db:"attempts"`
	MaxAttempts int             `json:"maxAttempts" db:"max_attempts"`
	LockedAt    *time.Time      `json:"lockedAt" db:"locked_at"`
	FinishedAt  *time.Time      `json:"finishedAt" db:"finished_at"`
	LastError   *string         `json:"lastError" db:"last_error"`
	CreatedAt   time.Time       `json:"createdAt" db:"created_at"`
	UniqueKey   *string         `json:"uniqueKey" db:"unique_key"`
}

// Validate applies the rules of Job from schema.lidza.
func (v Job) Validate() error {
	var errs validate.Errors
	if v.Kind == "" {
		errs.Add("kind", "required", "required")
	}
	if v.State == "" {
		errs.Add("state", "required", "required")
	}
	return errs.Result()
}

// JobSchedule is a row of the job_schedule table.
type JobSchedule struct {
	Kind      string     `json:"kind" db:"kind"`
	Spec      string     `json:"spec" db:"spec"`
	NextRunAt time.Time  `json:"nextRunAt" db:"next_run_at"`
	LastRunAt *time.Time `json:"lastRunAt" db:"last_run_at"`
	LastJobID *string    `json:"lastJobId" db:"last_job_id"`
	UpdatedAt time.Time  `json:"updatedAt" db:"updated_at"`
}

// Validate applies the rules of JobSchedule from schema.lidza.
func (v JobSchedule) Validate() error {
	var errs validate.Errors
	if v.Spec == "" {
		errs.Add("spec", "required", "required")
	}
	return errs.Result()
}

// MailMessage is a row of the mail_message table.
type MailMessage struct {
	ID          string          `json:"id" db:"id"`
	Recipient   string          `json:"recipient" db:"recipient"`
	FromAddress *string         `json:"fromAddress" db:"from_address"`
	ReplyTo     *string         `json:"replyTo" db:"reply_to"`
	Headers     json.RawMessage `json:"headers" db:"headers"`
	Cc          []string        `json:"cc" db:"cc"`
	Bcc         []string        `json:"bcc" db:"bcc"`
	Attachments json.RawMessage `json:"attachments" db:"attachments"`
	Subject     string          `json:"subject" db:"subject"`
	Text        *string         `json:"text" db:"text"`
	HTML        *string         `json:"html" db:"html"`
	Template    *string         `json:"template" db:"template"`
	Status      string          `json:"status" db:"status"`
	ProviderID  *string         `json:"providerId" db:"provider_id"`
	Error       *string         `json:"error" db:"error"`
	Attempts    int             `json:"attempts" db:"attempts"`
	CreatedAt   time.Time       `json:"createdAt" db:"created_at"`
	SentAt      *time.Time      `json:"sentAt" db:"sent_at"`
}

// Validate applies the rules of MailMessage from schema.lidza.
func (v MailMessage) Validate() error {
	var errs validate.Errors
	if v.Recipient == "" {
		errs.Add("recipient", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.Status == "" {
		errs.Add("status", "required", "required")
	}
	return errs.Result()
}

// DriveFolder is a row of the drive_folder table.
type DriveFolder struct {
	ID          string    `json:"id" db:"id"`
	WorkspaceID string    `json:"workspaceId" db:"workspace_id"`
	ParentID    *string   `json:"parentId" db:"parent_id"`
	Name        string    `json:"name" db:"name"`
	CreatedAt   time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of DriveFolder from schema.lidza.
func (v DriveFolder) Validate() error {
	var errs validate.Errors
	if v.WorkspaceID == "" {
		errs.Add("workspaceId", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	return errs.Result()
}

// DriveFile is a row of the drive_file table.
type DriveFile struct {
	ID             string    `json:"id" db:"id"`
	WorkspaceID    string    `json:"workspaceId" db:"workspace_id"`
	FolderID       *string   `json:"folderId" db:"folder_id"`
	Name           string    `json:"name" db:"name"`
	ContentType    string    `json:"contentType" db:"content_type"`
	Size           int       `json:"size" db:"size"`
	CurrentVersion int       `json:"currentVersion" db:"current_version"`
	Trashed        bool      `json:"trashed" db:"trashed"`
	CreatedAt      time.Time `json:"createdAt" db:"created_at"`
	UpdatedAt      time.Time `json:"updatedAt" db:"updated_at"`
}

// Validate applies the rules of DriveFile from schema.lidza.
func (v DriveFile) Validate() error {
	var errs validate.Errors
	if v.WorkspaceID == "" {
		errs.Add("workspaceId", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	if v.ContentType == "" {
		errs.Add("contentType", "required", "required")
	}
	return errs.Result()
}

// FileVersion is a row of the file_version table.
type FileVersion struct {
	ID        string    `json:"id" db:"id"`
	FileID    string    `json:"fileId" db:"file_id"`
	Number    int       `json:"number" db:"number"`
	ObjectKey string    `json:"objectKey" db:"object_key"`
	Checksum  string    `json:"checksum" db:"checksum"`
	Size      int       `json:"size" db:"size"`
	CreatedBy string    `json:"createdBy" db:"created_by"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of FileVersion from schema.lidza.
func (v FileVersion) Validate() error {
	var errs validate.Errors
	if v.FileID == "" {
		errs.Add("fileId", "required", "required")
	}
	if v.ObjectKey == "" {
		errs.Add("objectKey", "required", "required")
	}
	if v.Checksum == "" {
		errs.Add("checksum", "required", "required")
	}
	if v.CreatedBy == "" {
		errs.Add("createdBy", "required", "required")
	}
	return errs.Result()
}

// UploadSession is a row of the upload_session table.
type UploadSession struct {
	ID           string     `json:"id" db:"id"`
	WorkspaceID  string     `json:"workspaceId" db:"workspace_id"`
	Subject      string     `json:"subject" db:"subject"`
	FileID       *string    `json:"fileId" db:"file_id"`
	FolderID     *string    `json:"folderId" db:"folder_id"`
	Name         string     `json:"name" db:"name"`
	ContentType  string     `json:"contentType" db:"content_type"`
	ExpectedSize int        `json:"expectedSize" db:"expected_size"`
	BaseVersion  int        `json:"baseVersion" db:"base_version"`
	ExpiresAt    time.Time  `json:"expiresAt" db:"expires_at"`
	CompletedAt  *time.Time `json:"completedAt" db:"completed_at"`
	CreatedAt    time.Time  `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of UploadSession from schema.lidza.
func (v UploadSession) Validate() error {
	var errs validate.Errors
	if v.WorkspaceID == "" {
		errs.Add("workspaceId", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if v.ContentType == "" {
		errs.Add("contentType", "required", "required")
	}
	return errs.Result()
}

// UploadChunk is a row of the upload_chunk table.
type UploadChunk struct {
	ID        string `json:"id" db:"id"`
	SessionID string `json:"sessionId" db:"session_id"`
	Number    int    `json:"number" db:"number"`
	Size      int    `json:"size" db:"size"`
	Checksum  string `json:"checksum" db:"checksum"`
	ObjectKey string `json:"objectKey" db:"object_key"`
}

// Validate applies the rules of UploadChunk from schema.lidza.
func (v UploadChunk) Validate() error {
	var errs validate.Errors
	if v.SessionID == "" {
		errs.Add("sessionId", "required", "required")
	}
	if v.Checksum == "" {
		errs.Add("checksum", "required", "required")
	}
	if v.ObjectKey == "" {
		errs.Add("objectKey", "required", "required")
	}
	return errs.Result()
}

// ShareGrant is a row of the share_grant table.
type ShareGrant struct {
	ID          string     `json:"id" db:"id"`
	FileID      string     `json:"fileId" db:"file_id"`
	TokenHash   string     `json:"tokenHash" db:"token_hash"`
	TargetEmail string     `json:"targetEmail" db:"target_email"`
	ExpiresAt   time.Time  `json:"expiresAt" db:"expires_at"`
	RevokedAt   *time.Time `json:"revokedAt" db:"revoked_at"`
	CreatedAt   time.Time  `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of ShareGrant from schema.lidza.
func (v ShareGrant) Validate() error {
	var errs validate.Errors
	if v.FileID == "" {
		errs.Add("fileId", "required", "required")
	}
	if v.TokenHash == "" {
		errs.Add("tokenHash", "required", "required")
	}
	if v.TargetEmail == "" {
		errs.Add("targetEmail", "required", "required")
	}
	return errs.Result()
}

// OfficeSession is a row of the office_session table.
type OfficeSession struct {
	ID            string    `json:"id" db:"id"`
	FileID        string    `json:"fileId" db:"file_id"`
	Subject       string    `json:"subject" db:"subject"`
	SourceVersion int       `json:"sourceVersion" db:"source_version"`
	BaseVersion   int       `json:"baseVersion" db:"base_version"`
	DocumentKey   string    `json:"documentKey" db:"document_key"`
	LastChecksum  string    `json:"lastChecksum" db:"last_checksum"`
	ExpiresAt     time.Time `json:"expiresAt" db:"expires_at"`
	CreatedAt     time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of OfficeSession from schema.lidza.
func (v OfficeSession) Validate() error {
	var errs validate.Errors
	if v.FileID == "" {
		errs.Add("fileId", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.DocumentKey == "" {
		errs.Add("documentKey", "required", "required")
	}
	if v.LastChecksum == "" {
		errs.Add("lastChecksum", "required", "required")
	}
	return errs.Result()
}

// Calendar is a row of the calendar table.
type Calendar struct {
	ID           string    `json:"id" db:"id"`
	WorkspaceID  string    `json:"workspaceId" db:"workspace_id"`
	Name         string    `json:"name" db:"name"`
	Color        string    `json:"color" db:"color"`
	OwnerSubject *string   `json:"ownerSubject" db:"owner_subject"`
	CreatedAt    time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of Calendar from schema.lidza.
func (v Calendar) Validate() error {
	var errs validate.Errors
	if v.WorkspaceID == "" {
		errs.Add("workspaceId", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	if v.Color == "" {
		errs.Add("color", "required", "required")
	}
	return errs.Result()
}

// CalendarEvent is a row of the calendar_event table.
type CalendarEvent struct {
	ID          string     `json:"id" db:"id"`
	CalendarID  string     `json:"calendarId" db:"calendar_id"`
	Uid         string     `json:"uid" db:"uid"`
	Organizer   string     `json:"organizer" db:"organizer"`
	Title       string     `json:"title" db:"title"`
	Description string     `json:"description" db:"description"`
	Location    string     `json:"location" db:"location"`
	AllDay      bool       `json:"allDay" db:"all_day"`
	StartDate   string     `json:"startDate" db:"start_date"`
	EndDate     string     `json:"endDate" db:"end_date"`
	StartsAt    *time.Time `json:"startsAt" db:"starts_at"`
	EndsAt      *time.Time `json:"endsAt" db:"ends_at"`
	TimeZone    string     `json:"timeZone" db:"time_zone"`
	Rrule       string     `json:"rrule" db:"rrule"`
	Sequence    int        `json:"sequence" db:"sequence"`
	Cancelled   bool       `json:"cancelled" db:"cancelled"`
	CreatedAt   time.Time  `json:"createdAt" db:"created_at"`
	UpdatedAt   time.Time  `json:"updatedAt" db:"updated_at"`
}

// Validate applies the rules of CalendarEvent from schema.lidza.
func (v CalendarEvent) Validate() error {
	var errs validate.Errors
	if v.CalendarID == "" {
		errs.Add("calendarId", "required", "required")
	}
	if v.Uid == "" {
		errs.Add("uid", "required", "required")
	}
	if v.Organizer == "" {
		errs.Add("organizer", "required", "required")
	}
	if v.Title == "" {
		errs.Add("title", "required", "required")
	}
	if len(v.Title) < 1 {
		errs.Add("title", "min", "at least 1 character(s)")
	}
	if len(v.Title) > 500 {
		errs.Add("title", "max", "at most 500 character(s)")
	}
	if v.Description == "" {
		errs.Add("description", "required", "required")
	}
	if v.Location == "" {
		errs.Add("location", "required", "required")
	}
	if v.StartDate == "" {
		errs.Add("startDate", "required", "required")
	}
	if v.EndDate == "" {
		errs.Add("endDate", "required", "required")
	}
	if v.TimeZone == "" {
		errs.Add("timeZone", "required", "required")
	}
	if v.Rrule == "" {
		errs.Add("rrule", "required", "required")
	}
	return errs.Result()
}

// EventException is a row of the event_exception table.
type EventException struct {
	ID          string     `json:"id" db:"id"`
	EventID     string     `json:"eventId" db:"event_id"`
	InstanceKey string     `json:"instanceKey" db:"instance_key"`
	Cancelled   bool       `json:"cancelled" db:"cancelled"`
	Title       *string    `json:"title" db:"title"`
	StartsAt    *time.Time `json:"startsAt" db:"starts_at"`
	EndsAt      *time.Time `json:"endsAt" db:"ends_at"`
	StartDate   *string    `json:"startDate" db:"start_date"`
	EndDate     *string    `json:"endDate" db:"end_date"`
}

// Validate applies the rules of EventException from schema.lidza.
func (v EventException) Validate() error {
	var errs validate.Errors
	if v.EventID == "" {
		errs.Add("eventId", "required", "required")
	}
	if v.InstanceKey == "" {
		errs.Add("instanceKey", "required", "required")
	}
	return errs.Result()
}

// EventAttendee is a row of the event_attendee table.
type EventAttendee struct {
	ID               string     `json:"id" db:"id"`
	EventID          string     `json:"eventId" db:"event_id"`
	Email            string     `json:"email" db:"email"`
	Response         Attendance `json:"response" db:"response"`
	ResponseSequence int        `json:"responseSequence" db:"response_sequence"`
}

// Validate applies the rules of EventAttendee from schema.lidza.
func (v EventAttendee) Validate() error {
	var errs validate.Errors
	if v.EventID == "" {
		errs.Add("eventId", "required", "required")
	}
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if v.Email != "" && !validate.Email(v.Email) {
		errs.Add("email", "email", "not an email address")
	}
	if v.Response == "" {
		errs.Add("response", "required", "required")
	}
	if v.Response != "" && !v.Response.Valid() {
		errs.Add("response", "enum", "unknown Attendance value")
	}
	return errs.Result()
}

// CalendarReplyGrant is a row of the calendar_reply_grant table.
type CalendarReplyGrant struct {
	ID          string    `json:"id" db:"id"`
	AttendeeID  string    `json:"attendeeId" db:"attendee_id"`
	TokenHash   string    `json:"tokenHash" db:"token_hash"`
	Sequence    int       `json:"sequence" db:"sequence"`
	InstanceKey string    `json:"instanceKey" db:"instance_key"`
	ExpiresAt   time.Time `json:"expiresAt" db:"expires_at"`
	CreatedAt   time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of CalendarReplyGrant from schema.lidza.
func (v CalendarReplyGrant) Validate() error {
	var errs validate.Errors
	if v.AttendeeID == "" {
		errs.Add("attendeeId", "required", "required")
	}
	if v.TokenHash == "" {
		errs.Add("tokenHash", "required", "required")
	}
	if v.InstanceKey == "" {
		errs.Add("instanceKey", "required", "required")
	}
	return errs.Result()
}

// CalendarDispatch is a row of the calendar_dispatch table.
type CalendarDispatch struct {
	ID          string    `json:"id" db:"id"`
	EventID     string    `json:"eventId" db:"event_id"`
	Sequence    int       `json:"sequence" db:"sequence"`
	InstanceKey string    `json:"instanceKey" db:"instance_key"`
	CreatedAt   time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of CalendarDispatch from schema.lidza.
func (v CalendarDispatch) Validate() error {
	var errs validate.Errors
	if v.EventID == "" {
		errs.Add("eventId", "required", "required")
	}
	if v.InstanceKey == "" {
		errs.Add("instanceKey", "required", "required")
	}
	return errs.Result()
}

// CalendarReminder is a row of the calendar_reminder table.
type CalendarReminder struct {
	ID            string    `json:"id" db:"id"`
	EventID       string    `json:"eventId" db:"event_id"`
	Subject       string    `json:"subject" db:"subject"`
	MinutesBefore int       `json:"minutesBefore" db:"minutes_before"`
	CreatedAt     time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of CalendarReminder from schema.lidza.
func (v CalendarReminder) Validate() error {
	var errs validate.Errors
	if v.EventID == "" {
		errs.Add("eventId", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	return errs.Result()
}

// ReminderNotice is a row of the reminder_notice table.
type ReminderNotice struct {
	ID          string    `json:"id" db:"id"`
	EventID     string    `json:"eventId" db:"event_id"`
	Subject     string    `json:"subject" db:"subject"`
	Sequence    int       `json:"sequence" db:"sequence"`
	InstanceKey string    `json:"instanceKey" db:"instance_key"`
	CreatedAt   time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of ReminderNotice from schema.lidza.
func (v ReminderNotice) Validate() error {
	var errs validate.Errors
	if v.EventID == "" {
		errs.Add("eventId", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.InstanceKey == "" {
		errs.Add("instanceKey", "required", "required")
	}
	return errs.Result()
}

// ChatRoom is a row of the chat_room table.
type ChatRoom struct {
	ID           string    `json:"id" db:"id"`
	WorkspaceID  string    `json:"workspaceId" db:"workspace_id"`
	MatrixRoomID string    `json:"matrixRoomId" db:"matrix_room_id"`
	RequestID    string    `json:"requestId" db:"request_id"`
	Name         string    `json:"name" db:"name"`
	Direct       bool      `json:"direct" db:"direct"`
	CreatedBy    string    `json:"createdBy" db:"created_by"`
	CreatedAt    time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of ChatRoom from schema.lidza.
func (v ChatRoom) Validate() error {
	var errs validate.Errors
	if v.WorkspaceID == "" {
		errs.Add("workspaceId", "required", "required")
	}
	if v.MatrixRoomID == "" {
		errs.Add("matrixRoomId", "required", "required")
	}
	if v.RequestID == "" {
		errs.Add("requestId", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	if v.CreatedBy == "" {
		errs.Add("createdBy", "required", "required")
	}
	return errs.Result()
}

// ChatParticipant is a row of the chat_participant table.
type ChatParticipant struct {
	ID        string    `json:"id" db:"id"`
	RoomID    string    `json:"roomId" db:"room_id"`
	Subject   string    `json:"subject" db:"subject"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of ChatParticipant from schema.lidza.
func (v ChatParticipant) Validate() error {
	var errs validate.Errors
	if v.RoomID == "" {
		errs.Add("roomId", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	return errs.Result()
}

// Meeting is a row of the meeting table.
type Meeting struct {
	ID          string     `json:"id" db:"id"`
	WorkspaceID string     `json:"workspaceId" db:"workspace_id"`
	RequestID   string     `json:"requestId" db:"request_id"`
	Name        string     `json:"name" db:"name"`
	CreatedBy   string     `json:"createdBy" db:"created_by"`
	EndedAt     *time.Time `json:"endedAt" db:"ended_at"`
	CreatedAt   time.Time  `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of Meeting from schema.lidza.
func (v Meeting) Validate() error {
	var errs validate.Errors
	if v.WorkspaceID == "" {
		errs.Add("workspaceId", "required", "required")
	}
	if v.RequestID == "" {
		errs.Add("requestId", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	if v.CreatedBy == "" {
		errs.Add("createdBy", "required", "required")
	}
	return errs.Result()
}

// MeetingParticipant is a row of the meeting_participant table.
type MeetingParticipant struct {
	ID             string    `json:"id" db:"id"`
	MeetingID      string    `json:"meetingId" db:"meeting_id"`
	Subject        string    `json:"subject" db:"subject"`
	TokenExpiresAt time.Time `json:"tokenExpiresAt" db:"token_expires_at"`
	Joined         bool      `json:"joined" db:"joined"`
	SessionID      string    `json:"sessionId" db:"session_id"`
	UpdatedAt      time.Time `json:"updatedAt" db:"updated_at"`
}

// Validate applies the rules of MeetingParticipant from schema.lidza.
func (v MeetingParticipant) Validate() error {
	var errs validate.Errors
	if v.MeetingID == "" {
		errs.Add("meetingId", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.SessionID == "" {
		errs.Add("sessionId", "required", "required")
	}
	return errs.Result()
}

// MeetingWebhook is a row of the meeting_webhook table.
type MeetingWebhook struct {
	ID        string    `json:"id" db:"id"`
	EventID   string    `json:"eventId" db:"event_id"`
	Checksum  string    `json:"checksum" db:"checksum"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of MeetingWebhook from schema.lidza.
func (v MeetingWebhook) Validate() error {
	var errs validate.Errors
	if v.EventID == "" {
		errs.Add("eventId", "required", "required")
	}
	if v.Checksum == "" {
		errs.Add("checksum", "required", "required")
	}
	return errs.Result()
}

// Greeting is an API type.
type Greeting struct {
	Name    string `json:"name"`
	Message string `json:"message"`
}

// Validate applies the rules of Greeting from schema.lidza.
func (v Greeting) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 100 {
		errs.Add("name", "max", "at most 100 character(s)")
	}
	if v.Message == "" {
		errs.Add("message", "required", "required")
	}
	return errs.Result()
}

// WorkspaceList is an API type.
type WorkspaceList struct {
	Items []Workspace `json:"items"`
}

// Validate applies the rules of WorkspaceList from schema.lidza.
func (v WorkspaceList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// ContactList is an API type.
type ContactList struct {
	Items []Contact `json:"items"`
}

// Validate applies the rules of ContactList from schema.lidza.
func (v ContactList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// ContactInput is an API type.
type ContactInput struct {
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Company  *string `json:"company"`
	Phone    *string `json:"phone"`
	Favorite bool    `json:"favorite"`
}

// Validate applies the rules of ContactInput from schema.lidza.
func (v ContactInput) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if len(v.Email) > 254 {
		errs.Add("email", "max", "at most 254 character(s)")
	}
	if v.Email != "" && !validate.Email(v.Email) {
		errs.Add("email", "email", "not an email address")
	}
	if v.Company != nil {
		x := *v.Company
		if len(x) > 200 {
			errs.Add("company", "max", "at most 200 character(s)")
		}
	}
	if v.Phone != nil {
		x := *v.Phone
		if len(x) > 80 {
			errs.Add("phone", "max", "at most 80 character(s)")
		}
	}
	return errs.Result()
}

// ProvisionAccountInput is an API type.
type ProvisionAccountInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// Validate applies the rules of ProvisionAccountInput from schema.lidza.
func (v ProvisionAccountInput) Validate() error {
	var errs validate.Errors
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if len(v.Email) > 254 {
		errs.Add("email", "max", "at most 254 character(s)")
	}
	if v.Email != "" && !validate.Email(v.Email) {
		errs.Add("email", "email", "not an email address")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	if v.Password == "" {
		errs.Add("password", "required", "required")
	}
	if len(v.Password) < 12 {
		errs.Add("password", "min", "at least 12 character(s)")
	}
	if len(v.Password) > 200 {
		errs.Add("password", "max", "at most 200 character(s)")
	}
	return errs.Result()
}

// CreateWorkspaceInput is an API type.
type CreateWorkspaceInput struct {
	Name       string `json:"name"`
	OwnerEmail string `json:"ownerEmail"`
}

// Validate applies the rules of CreateWorkspaceInput from schema.lidza.
func (v CreateWorkspaceInput) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 120 {
		errs.Add("name", "max", "at most 120 character(s)")
	}
	if v.OwnerEmail == "" {
		errs.Add("ownerEmail", "required", "required")
	}
	if len(v.OwnerEmail) > 254 {
		errs.Add("ownerEmail", "max", "at most 254 character(s)")
	}
	if v.OwnerEmail != "" && !validate.Email(v.OwnerEmail) {
		errs.Add("ownerEmail", "email", "not an email address")
	}
	return errs.Result()
}

// InviteInput is an API type.
type InviteInput struct {
	Email string        `json:"email"`
	Role  WorkspaceRole `json:"role"`
}

// Validate applies the rules of InviteInput from schema.lidza.
func (v InviteInput) Validate() error {
	var errs validate.Errors
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if len(v.Email) > 254 {
		errs.Add("email", "max", "at most 254 character(s)")
	}
	if v.Email != "" && !validate.Email(v.Email) {
		errs.Add("email", "email", "not an email address")
	}
	if v.Role == "" {
		errs.Add("role", "required", "required")
	}
	if v.Role != "" && !v.Role.Valid() {
		errs.Add("role", "enum", "unknown WorkspaceRole value")
	}
	return errs.Result()
}

// InviteView is an API type.
type InviteView struct {
	ID         string        `json:"id"`
	Email      string        `json:"email"`
	Role       WorkspaceRole `json:"role"`
	ExpiresAt  time.Time     `json:"expiresAt"`
	AcceptedAt *time.Time    `json:"acceptedAt"`
	RevokedAt  *time.Time    `json:"revokedAt"`
}

// Validate applies the rules of InviteView from schema.lidza.
func (v InviteView) Validate() error {
	var errs validate.Errors
	if v.ID == "" {
		errs.Add("id", "required", "required")
	}
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if v.Role == "" {
		errs.Add("role", "required", "required")
	}
	if v.Role != "" && !v.Role.Valid() {
		errs.Add("role", "enum", "unknown WorkspaceRole value")
	}
	return errs.Result()
}

// InviteList is an API type.
type InviteList struct {
	Items []InviteView `json:"items"`
}

// Validate applies the rules of InviteList from schema.lidza.
func (v InviteList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// AcceptInviteInput is an API type.
type AcceptInviteInput struct {
	Token    string  `json:"token"`
	Name     *string `json:"name"`
	Password *string `json:"password"`
}

// Validate applies the rules of AcceptInviteInput from schema.lidza.
func (v AcceptInviteInput) Validate() error {
	var errs validate.Errors
	if v.Token == "" {
		errs.Add("token", "required", "required")
	}
	if len(v.Token) < 20 {
		errs.Add("token", "min", "at least 20 character(s)")
	}
	if len(v.Token) > 200 {
		errs.Add("token", "max", "at most 200 character(s)")
	}
	if v.Name != nil {
		x := *v.Name
		if len(x) > 200 {
			errs.Add("name", "max", "at most 200 character(s)")
		}
	}
	if v.Password != nil {
		x := *v.Password
		if len(x) > 200 {
			errs.Add("password", "max", "at most 200 character(s)")
		}
	}
	return errs.Result()
}

// MemberView is an API type.
type MemberView struct {
	Subject string        `json:"subject"`
	Email   string        `json:"email"`
	Name    string        `json:"name"`
	Role    WorkspaceRole `json:"role"`
}

// Validate applies the rules of MemberView from schema.lidza.
func (v MemberView) Validate() error {
	var errs validate.Errors
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if v.Role == "" {
		errs.Add("role", "required", "required")
	}
	if v.Role != "" && !v.Role.Valid() {
		errs.Add("role", "enum", "unknown WorkspaceRole value")
	}
	return errs.Result()
}

// MemberList is an API type.
type MemberList struct {
	Items []MemberView `json:"items"`
}

// Validate applies the rules of MemberList from schema.lidza.
func (v MemberList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// RoleInput is an API type.
type RoleInput struct {
	Role WorkspaceRole `json:"role"`
}

// Validate applies the rules of RoleInput from schema.lidza.
func (v RoleInput) Validate() error {
	var errs validate.Errors
	if v.Role == "" {
		errs.Add("role", "required", "required")
	}
	if v.Role != "" && !v.Role.Valid() {
		errs.Add("role", "enum", "unknown WorkspaceRole value")
	}
	return errs.Result()
}

// MailboxList is an API type.
type MailboxList struct {
	Items []Mailbox `json:"items"`
}

// Validate applies the rules of MailboxList from schema.lidza.
func (v MailboxList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// MailItemList is an API type.
type MailItemList struct {
	Items []MailItem `json:"items"`
}

// Validate applies the rules of MailItemList from schema.lidza.
func (v MailItemList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// AttachmentView is an API type.
type AttachmentView struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	ContentType string `json:"contentType"`
	Size        int    `json:"size"`
}

// Validate applies the rules of AttachmentView from schema.lidza.
func (v AttachmentView) Validate() error {
	var errs validate.Errors
	if v.ID == "" {
		errs.Add("id", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if v.ContentType == "" {
		errs.Add("contentType", "required", "required")
	}
	return errs.Result()
}

// MailDetail is an API type.
type MailDetail struct {
	Item        MailItem         `json:"item"`
	Attachments []AttachmentView `json:"attachments"`
}

// Validate applies the rules of MailDetail from schema.lidza.
func (v MailDetail) Validate() error {
	var errs validate.Errors
	if err := v.Item.Validate(); err != nil {
		errs.Add("item", "nested", err.Error())
	}
	for _, x := range v.Attachments {
		if err := x.Validate(); err != nil {
			errs.Add("attachments", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// DraftInput is an API type.
type DraftInput struct {
	To       *string `json:"to"`
	Cc       *string `json:"cc"`
	Bcc      *string `json:"bcc"`
	Subject  *string `json:"subject"`
	Text     *string `json:"text"`
	HTML     *string `json:"html"`
	ThreadID *string `json:"threadId"`
}

// Validate applies the rules of DraftInput from schema.lidza.
func (v DraftInput) Validate() error {
	var errs validate.Errors
	if v.To != nil {
		x := *v.To
		if len(x) > 2000 {
			errs.Add("to", "max", "at most 2000 character(s)")
		}
	}
	if v.Cc != nil {
		x := *v.Cc
		if len(x) > 2000 {
			errs.Add("cc", "max", "at most 2000 character(s)")
		}
	}
	if v.Bcc != nil {
		x := *v.Bcc
		if len(x) > 2000 {
			errs.Add("bcc", "max", "at most 2000 character(s)")
		}
	}
	if v.Subject != nil {
		x := *v.Subject
		if len(x) > 500 {
			errs.Add("subject", "max", "at most 500 character(s)")
		}
	}
	if v.Text != nil {
		x := *v.Text
		if len(x) > 500000 {
			errs.Add("text", "max", "at most 500000 character(s)")
		}
	}
	if v.HTML != nil {
		x := *v.HTML
		if len(x) > 500000 {
			errs.Add("html", "max", "at most 500000 character(s)")
		}
	}
	if v.ThreadID != nil {
		x := *v.ThreadID
		if len(x) > 500 {
			errs.Add("threadId", "max", "at most 500 character(s)")
		}
	}
	return errs.Result()
}

// MailFlags is an API type.
type MailFlags struct {
	Folder  *MailFolder `json:"folder"`
	Starred *bool       `json:"starred"`
	Unread  *bool       `json:"unread"`
}

// Validate applies the rules of MailFlags from schema.lidza.
func (v MailFlags) Validate() error {
	var errs validate.Errors
	if v.Folder != nil {
		x := *v.Folder
		if x != "" && !x.Valid() {
			errs.Add("folder", "enum", "unknown MailFolder value")
		}
	}
	return errs.Result()
}

// SendMailInput is an API type.
type SendMailInput struct {
	SendAt *time.Time `json:"sendAt"`
}

// Validate applies the rules of SendMailInput from schema.lidza.
func (v SendMailInput) Validate() error {
	var errs validate.Errors
	return errs.Result()
}

// ProvisionMailboxInput is an API type.
type ProvisionMailboxInput struct {
	WorkspaceID  string  `json:"workspaceId"`
	Name         string  `json:"name"`
	Address      string  `json:"address"`
	ConfigPrefix *string `json:"configPrefix"`
}

// Validate applies the rules of ProvisionMailboxInput from schema.lidza.
func (v ProvisionMailboxInput) Validate() error {
	var errs validate.Errors
	if v.WorkspaceID == "" {
		errs.Add("workspaceId", "required", "required")
	}
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 120 {
		errs.Add("name", "max", "at most 120 character(s)")
	}
	if v.Address == "" {
		errs.Add("address", "required", "required")
	}
	if len(v.Address) > 254 {
		errs.Add("address", "max", "at most 254 character(s)")
	}
	if v.Address != "" && !validate.Email(v.Address) {
		errs.Add("address", "email", "not an email address")
	}
	if v.ConfigPrefix != nil {
		x := *v.ConfigPrefix
		if len(x) > 100 {
			errs.Add("configPrefix", "max", "at most 100 character(s)")
		}
	}
	return errs.Result()
}

// FileContent is an API type.
type FileContent struct {
	Name        string `json:"name"`
	ContentType string `json:"contentType"`
	Data        string `json:"data"`
}

// Validate applies the rules of FileContent from schema.lidza.
func (v FileContent) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if v.ContentType == "" {
		errs.Add("contentType", "required", "required")
	}
	if v.Data == "" {
		errs.Add("data", "required", "required")
	}
	return errs.Result()
}

// DriveListing is an API type.
type DriveListing struct {
	Folders []DriveFolder `json:"folders"`
	Files   []DriveFile   `json:"files"`
}

// Validate applies the rules of DriveListing from schema.lidza.
func (v DriveListing) Validate() error {
	var errs validate.Errors
	for _, x := range v.Folders {
		if err := x.Validate(); err != nil {
			errs.Add("folders", "nested", err.Error())
			break
		}
	}
	for _, x := range v.Files {
		if err := x.Validate(); err != nil {
			errs.Add("files", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// FolderInput is an API type.
type FolderInput struct {
	Name     string  `json:"name"`
	ParentID *string `json:"parentId"`
}

// Validate applies the rules of FolderInput from schema.lidza.
func (v FolderInput) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	return errs.Result()
}

// UploadInput is an API type.
type UploadInput struct {
	Name        string  `json:"name"`
	ContentType string  `json:"contentType"`
	Size        int     `json:"size"`
	FileID      *string `json:"fileId"`
	FolderID    *string `json:"folderId"`
	BaseVersion int     `json:"baseVersion"`
}

// Validate applies the rules of UploadInput from schema.lidza.
func (v UploadInput) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	if v.ContentType == "" {
		errs.Add("contentType", "required", "required")
	}
	if len(v.ContentType) > 200 {
		errs.Add("contentType", "max", "at most 200 character(s)")
	}
	if v.Size < 1 {
		errs.Add("size", "min", "at least 1")
	}
	if v.Size > 10485760 {
		errs.Add("size", "max", "at most 10485760")
	}
	if v.BaseVersion < 0 {
		errs.Add("baseVersion", "min", "at least 0")
	}
	return errs.Result()
}

// UploadState is an API type.
type UploadState struct {
	Session UploadSession `json:"session"`
	Chunks  []int         `json:"chunks"`
}

// Validate applies the rules of UploadState from schema.lidza.
func (v UploadState) Validate() error {
	var errs validate.Errors
	if err := v.Session.Validate(); err != nil {
		errs.Add("session", "nested", err.Error())
	}
	return errs.Result()
}

// DriveFlags is an API type.
type DriveFlags struct {
	Name     *string `json:"name"`
	FolderID *string `json:"folderId"`
	Trashed  bool    `json:"trashed"`
}

// Validate applies the rules of DriveFlags from schema.lidza.
func (v DriveFlags) Validate() error {
	var errs validate.Errors
	if v.Name != nil {
		x := *v.Name
		if len(x) < 1 {
			errs.Add("name", "min", "at least 1 character(s)")
		}
		if len(x) > 200 {
			errs.Add("name", "max", "at most 200 character(s)")
		}
	}
	return errs.Result()
}

// VersionView is an API type.
type VersionView struct {
	Number    int       `json:"number"`
	Checksum  string    `json:"checksum"`
	Size      int       `json:"size"`
	CreatedBy string    `json:"createdBy"`
	CreatedAt time.Time `json:"createdAt"`
}

// Validate applies the rules of VersionView from schema.lidza.
func (v VersionView) Validate() error {
	var errs validate.Errors
	if v.Checksum == "" {
		errs.Add("checksum", "required", "required")
	}
	if v.CreatedBy == "" {
		errs.Add("createdBy", "required", "required")
	}
	return errs.Result()
}

// VersionList is an API type.
type VersionList struct {
	Items []VersionView `json:"items"`
}

// Validate applies the rules of VersionList from schema.lidza.
func (v VersionList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// ShareInput is an API type.
type ShareInput struct {
	TargetEmail *string   `json:"targetEmail"`
	ExpiresAt   time.Time `json:"expiresAt"`
}

// Validate applies the rules of ShareInput from schema.lidza.
func (v ShareInput) Validate() error {
	var errs validate.Errors
	if v.TargetEmail != nil {
		x := *v.TargetEmail
		if x != "" && !validate.Email(x) {
			errs.Add("targetEmail", "email", "not an email address")
		}
	}
	return errs.Result()
}

// ShareView is an API type.
type ShareView struct {
	ID          string     `json:"id"`
	TargetEmail string     `json:"targetEmail"`
	ExpiresAt   time.Time  `json:"expiresAt"`
	RevokedAt   *time.Time `json:"revokedAt"`
}

// Validate applies the rules of ShareView from schema.lidza.
func (v ShareView) Validate() error {
	var errs validate.Errors
	if v.ID == "" {
		errs.Add("id", "required", "required")
	}
	if v.TargetEmail == "" {
		errs.Add("targetEmail", "required", "required")
	}
	return errs.Result()
}

// ShareList is an API type.
type ShareList struct {
	Items []ShareView `json:"items"`
}

// Validate applies the rules of ShareList from schema.lidza.
func (v ShareList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// ShareCreated is an API type.
type ShareCreated struct {
	Grant ShareView `json:"grant"`
	Token string    `json:"token"`
}

// Validate applies the rules of ShareCreated from schema.lidza.
func (v ShareCreated) Validate() error {
	var errs validate.Errors
	if err := v.Grant.Validate(); err != nil {
		errs.Add("grant", "nested", err.Error())
	}
	if v.Token == "" {
		errs.Add("token", "required", "required")
	}
	return errs.Result()
}

// OpenShareInput is an API type.
type OpenShareInput struct {
	Token string `json:"token"`
}

// Validate applies the rules of OpenShareInput from schema.lidza.
func (v OpenShareInput) Validate() error {
	var errs validate.Errors
	if v.Token == "" {
		errs.Add("token", "required", "required")
	}
	if len(v.Token) < 20 {
		errs.Add("token", "min", "at least 20 character(s)")
	}
	if len(v.Token) > 200 {
		errs.Add("token", "max", "at most 200 character(s)")
	}
	return errs.Result()
}

// OfficeConfig is an API type.
type OfficeConfig struct {
	ScriptURL string          `json:"scriptUrl"`
	Config    json.RawMessage `json:"config"`
}

// Validate applies the rules of OfficeConfig from schema.lidza.
func (v OfficeConfig) Validate() error {
	var errs validate.Errors
	if v.ScriptURL == "" {
		errs.Add("scriptUrl", "required", "required")
	}
	return errs.Result()
}

// OfficeCallback is an API type.
type OfficeCallback struct {
	Key    string  `json:"key"`
	Status int     `json:"status"`
	URL    *string `json:"url"`
	Token  *string `json:"token"`
}

// Validate applies the rules of OfficeCallback from schema.lidza.
func (v OfficeCallback) Validate() error {
	var errs validate.Errors
	if v.Key == "" {
		errs.Add("key", "required", "required")
	}
	return errs.Result()
}

// OfficeResult is an API type.
type OfficeResult struct {
	Error int `json:"error"`
}

// Validate applies the rules of OfficeResult from schema.lidza.
func (v OfficeResult) Validate() error {
	var errs validate.Errors
	return errs.Result()
}

// CalendarList is an API type.
type CalendarList struct {
	Items []Calendar `json:"items"`
}

// Validate applies the rules of CalendarList from schema.lidza.
func (v CalendarList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// CalendarInput is an API type.
type CalendarInput struct {
	Name     string `json:"name"`
	Color    string `json:"color"`
	Personal bool   `json:"personal"`
}

// Validate applies the rules of CalendarInput from schema.lidza.
func (v CalendarInput) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	if v.Color == "" {
		errs.Add("color", "required", "required")
	}
	if len(v.Color) > 7 {
		errs.Add("color", "max", "at most 7 character(s)")
	}
	return errs.Result()
}

// EventInput is an API type.
type EventInput struct {
	ResetExceptions bool       `json:"resetExceptions"`
	Title           string     `json:"title"`
	Description     *string    `json:"description"`
	Location        *string    `json:"location"`
	AllDay          bool       `json:"allDay"`
	StartDate       *string    `json:"startDate"`
	EndDate         *string    `json:"endDate"`
	StartsAt        *time.Time `json:"startsAt"`
	EndsAt          *time.Time `json:"endsAt"`
	TimeZone        string     `json:"timeZone"`
	Rrule           *string    `json:"rrule"`
	Sequence        int        `json:"sequence"`
	Attendees       []string   `json:"attendees"`
}

// Validate applies the rules of EventInput from schema.lidza.
func (v EventInput) Validate() error {
	var errs validate.Errors
	if v.Title == "" {
		errs.Add("title", "required", "required")
	}
	if len(v.Title) < 1 {
		errs.Add("title", "min", "at least 1 character(s)")
	}
	if len(v.Title) > 500 {
		errs.Add("title", "max", "at most 500 character(s)")
	}
	if v.Description != nil {
		x := *v.Description
		if len(x) > 20000 {
			errs.Add("description", "max", "at most 20000 character(s)")
		}
	}
	if v.Location != nil {
		x := *v.Location
		if len(x) > 1000 {
			errs.Add("location", "max", "at most 1000 character(s)")
		}
	}
	if v.TimeZone == "" {
		errs.Add("timeZone", "required", "required")
	}
	if len(v.TimeZone) < 1 {
		errs.Add("timeZone", "min", "at least 1 character(s)")
	}
	if len(v.TimeZone) > 100 {
		errs.Add("timeZone", "max", "at most 100 character(s)")
	}
	if v.Rrule != nil {
		x := *v.Rrule
		if len(x) > 500 {
			errs.Add("rrule", "max", "at most 500 character(s)")
		}
	}
	if v.Sequence < 0 {
		errs.Add("sequence", "min", "at least 0")
	}
	return errs.Result()
}

// EventDetail is an API type.
type EventDetail struct {
	Event      CalendarEvent    `json:"event"`
	Attendees  []EventAttendee  `json:"attendees"`
	Exceptions []EventException `json:"exceptions"`
}

// Validate applies the rules of EventDetail from schema.lidza.
func (v EventDetail) Validate() error {
	var errs validate.Errors
	if err := v.Event.Validate(); err != nil {
		errs.Add("event", "nested", err.Error())
	}
	for _, x := range v.Attendees {
		if err := x.Validate(); err != nil {
			errs.Add("attendees", "nested", err.Error())
			break
		}
	}
	for _, x := range v.Exceptions {
		if err := x.Validate(); err != nil {
			errs.Add("exceptions", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// CalendarEvents is an API type.
type CalendarEvents struct {
	Items []EventDetail `json:"items"`
}

// Validate applies the rules of CalendarEvents from schema.lidza.
func (v CalendarEvents) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// EventInstance is an API type.
type EventInstance struct {
	EventID     string `json:"eventId"`
	CalendarID  string `json:"calendarId"`
	InstanceKey string `json:"instanceKey"`
	Title       string `json:"title"`
	Location    string `json:"location"`
	AllDay      bool   `json:"allDay"`
	Start       string `json:"start"`
	End         string `json:"end"`
	Color       string `json:"color"`
	Sequence    int    `json:"sequence"`
}

// Validate applies the rules of EventInstance from schema.lidza.
func (v EventInstance) Validate() error {
	var errs validate.Errors
	if v.EventID == "" {
		errs.Add("eventId", "required", "required")
	}
	if v.CalendarID == "" {
		errs.Add("calendarId", "required", "required")
	}
	if v.InstanceKey == "" {
		errs.Add("instanceKey", "required", "required")
	}
	if v.Title == "" {
		errs.Add("title", "required", "required")
	}
	if v.Location == "" {
		errs.Add("location", "required", "required")
	}
	if v.Start == "" {
		errs.Add("start", "required", "required")
	}
	if v.End == "" {
		errs.Add("end", "required", "required")
	}
	if v.Color == "" {
		errs.Add("color", "required", "required")
	}
	return errs.Result()
}

// CalendarInstances is an API type.
type CalendarInstances struct {
	Items []EventInstance `json:"items"`
}

// Validate applies the rules of CalendarInstances from schema.lidza.
func (v CalendarInstances) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// ExceptionInput is an API type.
type ExceptionInput struct {
	InstanceKey string     `json:"instanceKey"`
	Sequence    int        `json:"sequence"`
	Cancelled   bool       `json:"cancelled"`
	Title       *string    `json:"title"`
	StartsAt    *time.Time `json:"startsAt"`
	EndsAt      *time.Time `json:"endsAt"`
	StartDate   *string    `json:"startDate"`
	EndDate     *string    `json:"endDate"`
}

// Validate applies the rules of ExceptionInput from schema.lidza.
func (v ExceptionInput) Validate() error {
	var errs validate.Errors
	if v.InstanceKey == "" {
		errs.Add("instanceKey", "required", "required")
	}
	if len(v.InstanceKey) < 1 {
		errs.Add("instanceKey", "min", "at least 1 character(s)")
	}
	if len(v.InstanceKey) > 100 {
		errs.Add("instanceKey", "max", "at most 100 character(s)")
	}
	if v.Sequence < 0 {
		errs.Add("sequence", "min", "at least 0")
	}
	if v.Title != nil {
		x := *v.Title
		if len(x) < 1 {
			errs.Add("title", "min", "at least 1 character(s)")
		}
		if len(x) > 500 {
			errs.Add("title", "max", "at most 500 character(s)")
		}
	}
	return errs.Result()
}

// AttendanceInput is an API type.
type AttendanceInput struct {
	Response Attendance `json:"response"`
	Sequence int        `json:"sequence"`
}

// Validate applies the rules of AttendanceInput from schema.lidza.
func (v AttendanceInput) Validate() error {
	var errs validate.Errors
	if v.Response == "" {
		errs.Add("response", "required", "required")
	}
	if v.Response != "" && !v.Response.Valid() {
		errs.Add("response", "enum", "unknown Attendance value")
	}
	if v.Sequence < 0 {
		errs.Add("sequence", "min", "at least 0")
	}
	return errs.Result()
}

// CalendarImportResult is an API type.
type CalendarImportResult struct {
	Imported int `json:"imported"`
	Ignored  int `json:"ignored"`
}

// Validate applies the rules of CalendarImportResult from schema.lidza.
func (v CalendarImportResult) Validate() error {
	var errs validate.Errors
	return errs.Result()
}

// CalendarInviteInput is an API type.
type CalendarInviteInput struct {
	Sequence    int     `json:"sequence"`
	InstanceKey *string `json:"instanceKey"`
}

// Validate applies the rules of CalendarInviteInput from schema.lidza.
func (v CalendarInviteInput) Validate() error {
	var errs validate.Errors
	if v.Sequence < 0 {
		errs.Add("sequence", "min", "at least 0")
	}
	if v.InstanceKey != nil {
		x := *v.InstanceKey
		if len(x) > 100 {
			errs.Add("instanceKey", "max", "at most 100 character(s)")
		}
	}
	return errs.Result()
}

// CalendarDispatchResult is an API type.
type CalendarDispatchResult struct {
	Queued   int  `json:"queued"`
	Captured bool `json:"captured"`
}

// Validate applies the rules of CalendarDispatchResult from schema.lidza.
func (v CalendarDispatchResult) Validate() error {
	var errs validate.Errors
	return errs.Result()
}

// CalendarReplyView is an API type.
type CalendarReplyView struct {
	Event       CalendarEvent `json:"event"`
	Email       string        `json:"email"`
	InstanceKey string        `json:"instanceKey"`
	Response    Attendance    `json:"response"`
	ExpiresAt   time.Time     `json:"expiresAt"`
}

// Validate applies the rules of CalendarReplyView from schema.lidza.
func (v CalendarReplyView) Validate() error {
	var errs validate.Errors
	if err := v.Event.Validate(); err != nil {
		errs.Add("event", "nested", err.Error())
	}
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if v.InstanceKey == "" {
		errs.Add("instanceKey", "required", "required")
	}
	if v.Response == "" {
		errs.Add("response", "required", "required")
	}
	if v.Response != "" && !v.Response.Valid() {
		errs.Add("response", "enum", "unknown Attendance value")
	}
	return errs.Result()
}

// CalendarReplyInput is an API type.
type CalendarReplyInput struct {
	Token       string     `json:"token"`
	Response    Attendance `json:"response"`
	InstanceKey *string    `json:"instanceKey"`
}

// Validate applies the rules of CalendarReplyInput from schema.lidza.
func (v CalendarReplyInput) Validate() error {
	var errs validate.Errors
	if v.Token == "" {
		errs.Add("token", "required", "required")
	}
	if len(v.Token) < 20 {
		errs.Add("token", "min", "at least 20 character(s)")
	}
	if len(v.Token) > 200 {
		errs.Add("token", "max", "at most 200 character(s)")
	}
	if v.Response == "" {
		errs.Add("response", "required", "required")
	}
	if v.Response != "" && !v.Response.Valid() {
		errs.Add("response", "enum", "unknown Attendance value")
	}
	if v.InstanceKey != nil {
		x := *v.InstanceKey
		if len(x) > 100 {
			errs.Add("instanceKey", "max", "at most 100 character(s)")
		}
	}
	return errs.Result()
}

// CalendarReplyICS is an API type.
type CalendarReplyICS struct {
	Token   string `json:"token"`
	Content string `json:"content"`
}

// Validate applies the rules of CalendarReplyICS from schema.lidza.
func (v CalendarReplyICS) Validate() error {
	var errs validate.Errors
	if v.Token == "" {
		errs.Add("token", "required", "required")
	}
	if len(v.Token) < 20 {
		errs.Add("token", "min", "at least 20 character(s)")
	}
	if len(v.Token) > 200 {
		errs.Add("token", "max", "at most 200 character(s)")
	}
	if v.Content == "" {
		errs.Add("content", "required", "required")
	}
	if len(v.Content) > 100000 {
		errs.Add("content", "max", "at most 100000 character(s)")
	}
	return errs.Result()
}

// ReminderInput is an API type.
type ReminderInput struct {
	MinutesBefore *int `json:"minutesBefore"`
}

// Validate applies the rules of ReminderInput from schema.lidza.
func (v ReminderInput) Validate() error {
	var errs validate.Errors
	if v.MinutesBefore != nil {
		x := *v.MinutesBefore
		if x < 1 {
			errs.Add("minutesBefore", "min", "at least 1")
		}
		if x > 10080 {
			errs.Add("minutesBefore", "max", "at most 10080")
		}
	}
	return errs.Result()
}

// ReminderSetting is an API type.
type ReminderSetting struct {
	MinutesBefore *int `json:"minutesBefore"`
}

// Validate applies the rules of ReminderSetting from schema.lidza.
func (v ReminderSetting) Validate() error {
	var errs validate.Errors
	return errs.Result()
}

// ChatRoomInput is an API type.
type ChatRoomInput struct {
	Name        string  `json:"name"`
	RequestID   string  `json:"requestId"`
	Participant *string `json:"participant"`
}

// Validate applies the rules of ChatRoomInput from schema.lidza.
func (v ChatRoomInput) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	if v.RequestID == "" {
		errs.Add("requestId", "required", "required")
	}
	if v.Participant != nil {
		x := *v.Participant
		if len(x) > 200 {
			errs.Add("participant", "max", "at most 200 character(s)")
		}
	}
	return errs.Result()
}

// ChatRoomList is an API type.
type ChatRoomList struct {
	Items      []ChatRoom `json:"items"`
	Configured bool       `json:"configured"`
}

// Validate applies the rules of ChatRoomList from schema.lidza.
func (v ChatRoomList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// ChatSendInput is an API type.
type ChatSendInput struct {
	TransactionID string  `json:"transactionId"`
	Body          string  `json:"body"`
	ReplyTo       *string `json:"replyTo"`
}

// Validate applies the rules of ChatSendInput from schema.lidza.
func (v ChatSendInput) Validate() error {
	var errs validate.Errors
	if v.TransactionID == "" {
		errs.Add("transactionId", "required", "required")
	}
	if v.Body == "" {
		errs.Add("body", "required", "required")
	}
	if len(v.Body) < 1 {
		errs.Add("body", "min", "at least 1 character(s)")
	}
	if len(v.Body) > 10000 {
		errs.Add("body", "max", "at most 10000 character(s)")
	}
	if v.ReplyTo != nil {
		x := *v.ReplyTo
		if len(x) > 300 {
			errs.Add("replyTo", "max", "at most 300 character(s)")
		}
	}
	return errs.Result()
}

// ChatMessage is an API type.
type ChatMessage struct {
	ID        string           `json:"id"`
	Sender    string           `json:"sender"`
	Body      string           `json:"body"`
	Timestamp int              `json:"timestamp"`
	File      *ChatMessageFile `json:"file"`
	ReplyTo   *string          `json:"replyTo"`
}

// Validate applies the rules of ChatMessage from schema.lidza.
func (v ChatMessage) Validate() error {
	var errs validate.Errors
	if v.ID == "" {
		errs.Add("id", "required", "required")
	}
	if v.Sender == "" {
		errs.Add("sender", "required", "required")
	}
	if v.Body == "" {
		errs.Add("body", "required", "required")
	}
	if v.File != nil {
		x := *v.File
		if err := x.Validate(); err != nil {
			errs.Add("file", "nested", err.Error())
		}
	}
	return errs.Result()
}

// ChatTimeline is an API type.
type ChatTimeline struct {
	Items []ChatMessage `json:"items"`
	Next  *string       `json:"next"`
}

// Validate applies the rules of ChatTimeline from schema.lidza.
func (v ChatTimeline) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// ChatEventResult is an API type.
type ChatEventResult struct {
	EventID string `json:"eventId"`
}

// Validate applies the rules of ChatEventResult from schema.lidza.
func (v ChatEventResult) Validate() error {
	var errs validate.Errors
	if v.EventID == "" {
		errs.Add("eventId", "required", "required")
	}
	return errs.Result()
}

// ChatRemoteInput is an API type.
type ChatRemoteInput struct {
	UserID string `json:"userId"`
}

// Validate applies the rules of ChatRemoteInput from schema.lidza.
func (v ChatRemoteInput) Validate() error {
	var errs validate.Errors
	if v.UserID == "" {
		errs.Add("userId", "required", "required")
	}
	if len(v.UserID) < 4 {
		errs.Add("userId", "min", "at least 4 character(s)")
	}
	if len(v.UserID) > 254 {
		errs.Add("userId", "max", "at most 254 character(s)")
	}
	return errs.Result()
}

// ChatReceiptInput is an API type.
type ChatReceiptInput struct {
	EventID string `json:"eventId"`
}

// Validate applies the rules of ChatReceiptInput from schema.lidza.
func (v ChatReceiptInput) Validate() error {
	var errs validate.Errors
	if v.EventID == "" {
		errs.Add("eventId", "required", "required")
	}
	if len(v.EventID) < 1 {
		errs.Add("eventId", "min", "at least 1 character(s)")
	}
	if len(v.EventID) > 300 {
		errs.Add("eventId", "max", "at most 300 character(s)")
	}
	return errs.Result()
}

// ChatFileInput is an API type.
type ChatFileInput struct {
	TransactionID string `json:"transactionId"`
	FileID        string `json:"fileId"`
}

// Validate applies the rules of ChatFileInput from schema.lidza.
func (v ChatFileInput) Validate() error {
	var errs validate.Errors
	if v.TransactionID == "" {
		errs.Add("transactionId", "required", "required")
	}
	if v.FileID == "" {
		errs.Add("fileId", "required", "required")
	}
	return errs.Result()
}

// ChatMessageFile is an API type.
type ChatMessageFile struct {
	Name string `json:"name"`
	Size int    `json:"size"`
}

// Validate applies the rules of ChatMessageFile from schema.lidza.
func (v ChatMessageFile) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	return errs.Result()
}

// MeetingInput is an API type.
type MeetingInput struct {
	Name      string `json:"name"`
	RequestID string `json:"requestId"`
}

// Validate applies the rules of MeetingInput from schema.lidza.
func (v MeetingInput) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 200 {
		errs.Add("name", "max", "at most 200 character(s)")
	}
	if v.RequestID == "" {
		errs.Add("requestId", "required", "required")
	}
	return errs.Result()
}

// MeetingList is an API type.
type MeetingList struct {
	Items      []Meeting `json:"items"`
	Configured bool      `json:"configured"`
}

// Validate applies the rules of MeetingList from schema.lidza.
func (v MeetingList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// MeetingAccess is an API type.
type MeetingAccess struct {
	Token     string    `json:"token"`
	ServerURL string    `json:"serverUrl"`
	ExpiresAt time.Time `json:"expiresAt"`
	Meeting   Meeting   `json:"meeting"`
}

// Validate applies the rules of MeetingAccess from schema.lidza.
func (v MeetingAccess) Validate() error {
	var errs validate.Errors
	if v.Token == "" {
		errs.Add("token", "required", "required")
	}
	if v.ServerURL == "" {
		errs.Add("serverUrl", "required", "required")
	}
	if err := v.Meeting.Validate(); err != nil {
		errs.Add("meeting", "nested", err.Error())
	}
	return errs.Result()
}
