// Code generated by lidza gen from schema.lidza. DO NOT EDIT.

package schema

import (
	"github.com/agim/lidza/pkg/validate"
)

// Greeting is an API type.
type Greeting struct {
	Name    string `json:"name"`
	Message string `json:"message"`
}

// Validate applies the rules of Greeting from schema.lidza.
func (v Greeting) Validate() error {
	var errs validate.Errors
	if v.Name == "" {
		errs.Add("name", "required", "required")
	}
	if len(v.Name) < 1 {
		errs.Add("name", "min", "at least 1 character(s)")
	}
	if len(v.Name) > 100 {
		errs.Add("name", "max", "at most 100 character(s)")
	}
	if v.Message == "" {
		errs.Add("message", "required", "required")
	}
	return errs.Result()
}
