import { expect, test } from '@playwright/test'
test('Real Matrix channel sends, replies, reconnects, and shares a Drive file through Thura', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const name = `Real Matrix room ${Date.now()}`
  await page.goto('/app')
  await page.getByLabel('Email', { exact: true }).fill('owner-e2e@example.com')
  await page.getByLabel('Password', { exact: true }).fill('thura fixture maple lantern 4829')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Chat', exact: true }).click()
  await page.getByLabel('Room name', { exact: true }).fill(name)
  await page.getByRole('button', { name: 'Create room', exact: true }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  const body = `Real message ${Date.now()} <script>window.injected=true</script>`
  await page.getByLabel('Message', { exact: true }).fill(body)
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.getByLabel('Messages').getByText(body, { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Reply', exact: true }).last().click()
  await page.getByLabel('Message', { exact: true }).fill('Browser reply')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.getByLabel('Messages').getByText('Browser reply', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Chat', exact: true }).click()
  await page.getByLabel('Chat room', { exact: true }).selectOption({ label: name })
  await expect(page.getByLabel('Messages').getByText(body, { exact: true })).toBeVisible()
  const file = page.getByLabel('Share a Drive file').locator('option').nth(1)
  await expect(file).toBeAttached()
  const fileId = await file.getAttribute('value')
  const fileName = await file.textContent()
  await page.getByLabel('Share a Drive file').selectOption(fileId!)
  await page.getByRole('button', { name: 'Send file', exact: true }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: `Download ${fileName}`, exact: true }).click()
  expect((await download).suggestedFilename()).toBe(fileName)
  await page.getByRole('button', { name: 'Mark conversation read' }).click()
  expect(await page.evaluate(() => (window as unknown as { injected?: boolean }).injected)).toBeUndefined()
  expect(errors).toEqual([])
})
