import { expect, test } from '@playwright/test'
import path from 'node:path'
import { execFileSync } from 'node:child_process'

test('real ONLYOFFICE opens DOCX and saves an edited immutable version', async ({ page }) => {
  const name = `office-${Date.now()}.docx`
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/app')
  await page.getByLabel('Email', { exact: true }).fill('owner-e2e@example.com')
  await page.getByLabel('Password', { exact: true }).fill('thura fixture maple lantern 4829')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Drive', exact: true }).click()
  const buffer = await import('node:fs/promises').then(fs => fs.readFile(path.join(process.cwd(), 'integration/fixtures/office.docx')))
  await page.getByLabel('Upload file', { exact: true }).setInputFiles({ name, mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', buffer })
  await expect(page.getByRole('status')).toHaveText('Upload complete')
  await page.getByRole('button', { name: 'Edit document', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Editor connected.' })).toBeVisible({ timeout: 60000 })
  await page.screenshot({ path: '/tmp/thura-office-open.png', fullPage: true })
  const editor = page.frameLocator('.office-editor iframe')
  await editor.getByText('Got it', { exact: true }).click()
  await editor.locator('#id_viewer_overlay').click({ position: { x: 260, y: 160 } })
  await page.keyboard.press('Control+Home')
  await page.keyboard.type('Real saved edit. ')
  await page.keyboard.press('Control+s')
  await expect(page.getByRole('button', { name: 'Download version 2', exact: true })).toBeVisible({ timeout: 45000 })
  await expect(page.getByRole('button', { name: 'Download version 1', exact: true })).toBeVisible()
  const savedDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download version 2', exact: true }).click()
  const savedPath = await (await savedDownload).path()
  expect(savedPath).not.toBeNull()
  const savedText = execFileSync('python3', ['-c', 'import sys,zipfile,xml.etree.ElementTree as E; root=E.fromstring(zipfile.ZipFile(sys.argv[1]).read("word/document.xml")); print("".join(root.itertext()))', savedPath!], { encoding: 'utf8' })
  expect(savedText).toContain('Real saved edit.')
  expect(savedText).toContain('Original office fixture.')
  expect(errors).toEqual([])
})

test('real ONLYOFFICE opens XLSX and saves an edited immutable version', async ({ page }) => {
  const name = `sheet-${Date.now()}.xlsx`
  await page.goto('/app')
  await page.getByLabel('Email', { exact: true }).fill('owner-e2e@example.com')
  await page.getByLabel('Password', { exact: true }).fill('thura fixture maple lantern 4829')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Drive', exact: true }).click()
  const buffer = await import('node:fs/promises').then(fs => fs.readFile(path.join(process.cwd(), 'integration/fixtures/office.xlsx')))
  await page.getByLabel('Upload file', { exact: true }).setInputFiles({ name, mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer })
  await expect(page.getByRole('status')).toHaveText('Upload complete')
  await page.getByRole('button', { name: 'Edit document', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Editor connected.' })).toBeVisible({ timeout: 60000 })
  await page.screenshot({ path: '/tmp/thura-sheet-open.png', fullPage: true })
  const editor = page.frameLocator('.office-editor iframe')
  await editor.getByText('Got it', { exact: true }).click()
  const cell = editor.locator('#ce-cell-content')
  await cell.fill('Real saved sheet edit.')
  await cell.press('Enter')
  await page.keyboard.press('Control+s')
  await expect(page.getByRole('button', { name: 'Download version 2', exact: true })).toBeVisible({ timeout: 45000 })
  await expect(page.getByRole('button', { name: 'Download version 1', exact: true })).toBeVisible()
  const savedDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download version 2', exact: true }).click()
  const savedPath = await (await savedDownload).path()
  expect(savedPath).not.toBeNull()
  const savedXml = execFileSync('python3', ['-c', 'import sys,zipfile; z=zipfile.ZipFile(sys.argv[1]); print("".join(z.read(n).decode() for n in z.namelist() if n.startswith("xl/") and n.endswith(".xml")))', savedPath!], { encoding: 'utf8' })
  expect(savedXml).toContain('Real saved sheet edit.')
})
